### ISSUE TITLE
Unable to import numpy when script is called from other language

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#104]
When the following python function is exported by polyglot and called by other language,
java in this case, numpy cannot be imported. Is this by design?

```python
import polyglot
import datetime
import numpy as np

@polyglot.export_value
def data(filename):
  print(datetime.datetime.now())
  print('I will open \"' + filename + '\"')

  data = np.genfromtxt(filename, skip_header=5)
  print(data[:, 0])

if __name__ == '__main__':
  data("rae2822.txt")
```

```
Exception in thread "main" ModuleNotFoundError: No module named 'numpy'
	at <python> <module 'demo_polyglot.py'>(demo_polyglot.py:3:39-49)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:344)
	at main.main(main.java:40)
```

**Comment by timfel** [comment]
This is a consequence of the Python design. You have to run `import site` to get installed packages on the python path. Only the REPL does this automatically for you

**Comment by oroppas** [comment]
Thank you, @timfel 
After I put `import site` on top of the python script, I got the following error:

```
Exception in thread "main" Access to native code is not allowed by the host environment.
	at <python> <module 'overrides.py'>(../.local/lib/python3.7/site-packages/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/core/overrides.py:6-7:113-223)
	at <python> <module 'multiarray.py'>(../.local/lib/python3.7/site-packages/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/core/multiarray.py:12:305-327)
	at <python> <module '__init__.py'>(../.local/lib/python3.7/site-packages/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/core/__init__.py:40:1446-1469)
	at <python> <module '__init__.py'>(../.local/lib/python3.7/site-packages/numpy-1.16.4-py3.7-linux-x86_64.egg/numpy/__init__.py:142:4232-4249)
```

However, I create the context

```
      Context context = Context.newBuilder()
                               .out(myOut)
                               .allowIO(true)
                               .allowPolyglotAccess(PolyglotAccess.ALL)
                               .build();
```

such that all the languages are allowed. I have no issue import numpy by graalpython standalone.
Am I missing something?

**Comment by timfel** [comment]
You need to allow native access also.

**Comment by oroppas** [comment]
Ah, forgot `.allowNativeAccess(true)` during context build.
Thank you!

**Comment by timfel** [comment]
No problem :-) Great to see you trying this out!

**Comment by abvijaykumar** [comment]
I am not able to get numpy working in Graal. I keep getting 

```
Exception : 
RuntimeError: No active exception to reraise
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:353)
        at NumPyJavaExample.callPythonMethods(NumPyJavaExample.java:18)
        at NumPyJavaExample.main(NumPyJavaExample.java:39)

```
when ever I try to call a python function that uses numpy from Java

**Comment by timfel** [comment]
@abvijaykumar you wrote on slack you got it working with allowAllAccess. If there is anything more, could you please open a new issue?
