### ISSUE TITLE
External function PyDict_GetItemWithError cannot be found.

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#106]
When I run `graalpython setup.py test` on Cython from master branch from the repository
I got the following error:

```
Traceback (most recent call last):
External function PyDict_GetItemWithError cannot be found.
Traceback (most recent call last):
  File "setup.py", line 227, in <module 'setup.py'>
  "/home/ryutas/.local/lib/python3.7/site-packages/setuptools-41.0.1-py3.7.egg/setuptools/__init__.py", line 145, in setup
  File "core.py", line 148, in setup
  File "dist.py", line 966, in run_commands
  File "dist.py", line 985, in run_command
  "/home/ryutas/.local/lib/python3.7/site-packages/setuptools-41.0.1-py3.7.egg/setuptools/command/test.py", line 229, in run
  "/home/ryutas/.local/lib/python3.7/site-packages/setuptools-41.0.1-py3.7.egg/setuptools/command/test.py", line 247, in run_tests
  File "main.py", line 100, in __init__
  File "main.py", line 124, in parseArgs
  File "main.py", line 244, in _do_discovery
  File "main.py", line 154, in createTests
  File "loader.py", line 349, in discover
  File "loader.py", line 405, in _find_tests
  File "loader.py", line 483, in _find_test_path
  "/home/ryutas/.local/lib/python3.7/site-packages/setuptools-41.0.1-py3.7.egg/setuptools/command/test.py", line 55, in loadTestsFromModule
  File "loader.py", line 191, in loadTestsFromName
  "/home/ryutas/.local/lib/python3.7/site-packages/setuptools-41.0.1-py3.7.egg/setuptools/command/test.py", line 55, in loadTestsFromModule
  File "loader.py", line 154, in loadTestsFromName
  File "Inline.py", line 14, in <module 'Inline.py'>
  File "ParseTreeTransforms.py", line 1545, in <module 'ParseTreeTransforms.py'>
  File "ParseTreeTransforms.py", line 1547, in AnalyseDeclarationsTransform
  File "TreeFragment.py", line 235, in __init__
  File "TreeFragment.py", line 74, in parse_from_strings
External function PyDict_GetItemWithError cannot be found.
```
My graalpython does not have cython in local. The build was successful.
I'm a bit puzzled since `PyDict_GetItemWithError` seems to be implemented in graalpython already.

**Comment by timfel** [comment]
Can you try installing with `graalpython -m ginstall install Cython` instead/

**Comment by oroppas** [comment]
Okay, this particular version of Cython (0.29.13), graalpython can run test.
Sorry for the noise. Thanks as always.
