### ISSUE TITLE
[truffle] opt fail during creation of venv

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#107]
Hi,

I've got the following truffle failure when I try create `venv` so that I can try `scipy`:

```
$ graalpython -m venv gvenv
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
We're not using symlinks in a Graal Python venv
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
[truffle] opt fail         <builtin function register at 337e75fe>                     |Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: do not create a Node from compiled code 
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: do not create a Node from compiled code
	at com.oracle.truffle.api.nodes.Node.<init>(Node.java:107)
	at com.oracle.truffle.api.nodes.ExecutableNode.<init>(ExecutableNode.java:81)
	at com.oracle.truffle.api.nodes.RootNode.<init>(RootNode.java:158)
	at com.oracle.truffle.api.nodes.RootNode.<init>(RootNode.java:143)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltins$RegisterNode$AtExitCallTarget.<init>(AtexitModuleBuiltins.java:87)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltins$RegisterNode.register(AtexitModuleBuiltins.java:113)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltinsFactory$RegisterNodeFactory$RegisterNodeGen.execute(AtexitModuleBuiltinsFactory.java:75)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode$BuiltinVarArgsCallNode.execute(BuiltinFunctionRootNode.java:167)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode.execute(BuiltinFunctionRootNode.java:353)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:476)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:451)

[truffle] opt fail         <builtin function register at 337e75fe>                     |Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: do not create a Node from compiled code 
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: do not create a Node from compiled code
	at com.oracle.truffle.api.nodes.Node.<init>(Node.java:107)
	at com.oracle.truffle.api.nodes.ExecutableNode.<init>(ExecutableNode.java:81)
	at com.oracle.truffle.api.nodes.RootNode.<init>(RootNode.java:158)
	at com.oracle.truffle.api.nodes.RootNode.<init>(RootNode.java:143)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltins$RegisterNode$AtExitCallTarget.<init>(AtexitModuleBuiltins.java:87)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltins$RegisterNode.register(AtexitModuleBuiltins.java:113)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltinsFactory$RegisterNodeFactory$RegisterNodeGen.execute(AtexitModuleBuiltinsFactory.java:75)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode$BuiltinVarArgsCallNode.execute(BuiltinFunctionRootNode.java:167)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode.execute(BuiltinFunctionRootNode.java:353)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:476)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:451)

[truffle] opt fail         <function root update at 24d4ada7>                          |Reason org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Partial evaluation did not reduce value to a constant, is a regular compiler node: 2146|+ 
org.graalvm.compiler.code.SourceStackTraceBailoutException$1: Partial evaluation did not reduce value to a constant, is a regular compiler node: 2146|+
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: Partial evaluation did not reduce value to a constant, is a regular compiler node: 2146|+
	at org.graalvm.compiler.replacements.PEGraphDecoder$PENonAppendGraphBuilderContext.bailout(PEGraphDecoder.java:309)
	at org.graalvm.compiler.truffle.compiler.substitutions.TruffleGraphBuilderPlugins$PEConstantPlugin.apply(TruffleGraphBuilderPlugins.java:740)
	at org.graalvm.compiler.nodes.graphbuilderconf.InvocationPlugin.execute(InvocationPlugin.java:213)
	at org.graalvm.compiler.replacements.PEGraphDecoder.tryInvocationPlugin(PEGraphDecoder.java:797)
	at org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:718)
	at org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:698)
	at org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:584)
	at org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:415)
	at org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:621)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.doGraphPE(PartialEvaluator.java:592)
	at com.oracle.svm.truffle.api.SubstratePartialEvaluator.doGraphPE(SubstratePartialEvaluator.java:83)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.agnosticInliningOrGraphPE(PartialEvaluator.java:677)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.fastPartialEvaluation(PartialEvaluator.java:630)
	at org.graalvm.compiler.truffle.compiler.PartialEvaluator.createGraph(PartialEvaluator.java:276)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.compileAST(TruffleCompilerImpl.java:456)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:644)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl$TruffleCompilationWrapper.performCompilation(TruffleCompilerImpl.java:586)
	at org.graalvm.compiler.core.CompilationWrapper.run(CompilationWrapper.java:179)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.actuallyCompile(TruffleCompilerImpl.java:299)
	at org.graalvm.compiler.truffle.compiler.TruffleCompilerImpl.doCompile(TruffleCompilerImpl.java:267)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.compileImpl(GraalTruffleRuntime.java:713)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime.doCompile(GraalTruffleRuntime.java:694)
	at org.graalvm.compiler.truffle.runtime.GraalTruffleRuntime$1.execute(GraalTruffleRuntime.java:769)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$RequestImpl.call(BackgroundCompileQueue.java:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
	at org.graalvm.compiler.truffle.runtime.BackgroundCompileQueue$TruffleCompilerThreadFactory$1.run(BackgroundCompileQueue.java:233)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:502)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

**Comment by timfel** [comment]
Thanks for the report. This is not fatal, however, the venv will still be created correctly.

**Comment by timfel** [comment]
Fixed in master

**Comment by marad** [comment]
@timfel I'm implementing a toy language and get this error - how do you fix that?

**Comment by timfel** [comment]
@marad this isn't the right place to ask this question, better to hop on Slack. But to answer - do what the message says, you must not create nodes in compiled code. Before creating a node, do a `CompilerDirectives.transferToInterpreterAndInvalidate()`

**Comment by marad** [comment]
Thanks for the answer! It's the right thing to do, but to know exactly where to do this it's helpful to add an option `--engine.CompilationFailureAction=Diagnose`. It'll print the stack trace so you can exactly see where to put the `CompilerDirectives.transferToInterpreterAndInvalidate()`.

> this isn't the right place to ask this question

I feel like publicly available GH issue that is the only link returned by google on query "do not create a Node from compiled code" is exactly the place to ask and leave the answer for next generations of Truffle language implementers ;)
