### ISSUE TITLE
[truffle] opt fail during testing of pyparsing

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#108]
I've got the following truffle error while testing pyparsing:

```
graalpython ./setup.py test
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
running test
running egg_info
writing pyparsing.egg-info/PKG-INFO
writing dependency_links to pyparsing.egg-info/dependency_links.txt
writing top-level names to pyparsing.egg-info/top_level.txt
reading manifest file 'pyparsing.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'HowToUsePyparsing.rst'
warning: no files found matching 'pyparsingClassDiagram.*'
warning: no files found matching 'README.md'
warning: no files found matching 'modules.rst'
no previously-included directories found matching 'docs/_build/*'
writing manifest file 'pyparsing.egg-info/SOURCES.txt'
running build_ext
You are standing on the front porch of a wooden shack.
There are a mailbox and a shovel here.
>> 
[truffle] opt fail         <builtin function register at 337e75fe>                     |Reason org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: do not create a Node from compiled code 
org.graalvm.compiler.truffle.compiler.nodes.asserts.NeverPartOfCompilationNode$NeverPartOfCompilationException: do not create a Node from compiled code
	at com.oracle.truffle.api.nodes.Node.<init>(Node.java:107)
	at com.oracle.truffle.api.nodes.ExecutableNode.<init>(ExecutableNode.java:81)
	at com.oracle.truffle.api.nodes.RootNode.<init>(RootNode.java:158)
	at com.oracle.truffle.api.nodes.RootNode.<init>(RootNode.java:143)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltins$RegisterNode$AtExitCallTarget.<init>(AtexitModuleBuiltins.java:87)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltins$RegisterNode.register(AtexitModuleBuiltins.java:113)
	at com.oracle.graal.python.builtins.modules.AtexitModuleBuiltinsFactory$RegisterNodeFactory$RegisterNodeGen.execute(AtexitModuleBuiltinsFactory.java:75)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode$BuiltinVarArgsCallNode.execute(BuiltinFunctionRootNode.java:167)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode.execute(BuiltinFunctionRootNode.java:353)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:476)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:451)
```

**Comment by timfel** [comment]
Thanks for the report. This error is not fatal, however.

**Comment by timfel** [comment]
Fixed in master
