### ISSUE TITLE
Unexpected null when running python code in parallel in contexts sharing engine

### ISSUE THREAD

**Issue by zolstein** [graalvm/graalpython#113]
Possibly related to https://github.com/oracle/graal/issues/1942, tracking a similar-looking problem found when executing javascript.

Python code finds an unexpected null value when running code in parallel among multiple contexts sharing an engine. I've constructed a small test case demonstrating this (tested using GraalVM 19.2.0 and 19.3.0; I believe the issue exists on some versions prior to this but haven't personally tested them):

```java
public void testPythonMultithreaded() throws InterruptedException {
  Source code = Source.create("python", "lambda: 1");
  Engine engine = Engine.create();
  List<Thread> threads = new ArrayList<>();
  for (int i = 0; i < 10; i++) {
    Context context = Context.newBuilder().engine(engine).build();
    Runnable r = () -> System.out.println(context.eval(code).execute());
    threads.add(new Thread(r));
  }
  AtomicBoolean failure = new AtomicBoolean(false);
  for (Thread thread : threads) {
    thread.setUncaughtExceptionHandler(
        (t, e) -> {
          e.printStackTrace();
          failure.set(true);
        });
    thread.start();
  }
  for (Thread thread : threads) {
    thread.join();
  }
  assert !failure.get();
}
```

This produces (9 of) the following stacktrace:
```
org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for GetLazyClassNodeGen@2b0ee0db: [null], [null]
	at com.oracle.graal.python.nodes.object.GetLazyClassNodeGen.executeAndSpecialize(GetLazyClassNodeGen.java:374)
	at com.oracle.graal.python.nodes.object.GetLazyClassNodeGen.execute(GetLazyClassNodeGen.java:138)
	at com.oracle.graal.python.nodes.attributes.LookupInheritedAttributeNode.execute(LookupInheritedAttributeNode.java:79)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNode.callObject(LookupAndCallUnaryNode.java:212)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeAndSpecialize(LookupAndCallUnaryNodeGen.java:808)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeObject(LookupAndCallUnaryNodeGen.java:205)
	at com.oracle.graal.python.nodes.control.GetNextNode.execute(GetNextNode.java:82)
	at com.oracle.graal.python.nodes.control.ForNextElementNode.doIterator(ForNode.java:144)
	at com.oracle.graal.python.nodes.control.ForNextElementNodeGen.executeAndSpecialize(ForNextElementNodeGen.java:176)
	at com.oracle.graal.python.nodes.control.ForNextElementNodeGen.execute(ForNextElementNodeGen.java:72)
	at com.oracle.graal.python.nodes.control.ForRepeatingNode.executeRepeating(ForNode.java:72)
	at org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:135)
	at org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.executeLoop(OptimizedOSRLoopNode.java:112)
	at com.oracle.graal.python.nodes.control.ForNode.executeVoid(ForNode.java:188)
	at com.oracle.graal.python.nodes.control.ElseNode.executeVoid(ElseNode.java:51)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.ReturnTargetNode.execute(ReturnTargetNode.java:58)
	at com.oracle.graal.python.nodes.function.InnerRootNode.execute(InnerRootNode.java:66)
	at com.oracle.graal.python.nodes.function.FunctionRootNode.execute(FunctionRootNode.java:147)
	at org.graalvm.polyglot.Context.eval(Context.java:344)
	at execution.table.MultithreadedTest.lambda$testPythonMultithread$0(MultithreadedTest.java:23)
	at java.lang.Thread.run(Thread.java:748)
Original Internal Error: 
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for GetLazyClassNodeGen@2b0ee0db: [null], [null]
	at com.oracle.graal.python.nodes.object.GetLazyClassNodeGen.executeAndSpecialize(GetLazyClassNodeGen.java:374)
	at com.oracle.graal.python.nodes.object.GetLazyClassNodeGen.execute(GetLazyClassNodeGen.java:138)
	at com.oracle.graal.python.nodes.attributes.LookupInheritedAttributeNode.execute(LookupInheritedAttributeNode.java:79)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNode.callObject(LookupAndCallUnaryNode.java:212)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeAndSpecialize(LookupAndCallUnaryNodeGen.java:808)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeObject(LookupAndCallUnaryNodeGen.java:205)
	at com.oracle.graal.python.nodes.control.GetNextNode.execute(GetNextNode.java:82)
	at com.oracle.graal.python.nodes.control.ForNextElementNode.doIterator(ForNode.java:144)
	at com.oracle.graal.python.nodes.control.ForNextElementNodeGen.executeAndSpecialize(ForNextElementNodeGen.java:176)
	at com.oracle.graal.python.nodes.control.ForNextElementNodeGen.execute(ForNextElementNodeGen.java:72)
	at com.oracle.graal.python.nodes.control.ForRepeatingNode.executeRepeating(ForNode.java:72)
	at org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:135)
	at org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.executeLoop(OptimizedOSRLoopNode.java:112)
	at com.oracle.graal.python.nodes.control.ForNode.executeVoid(ForNode.java:188)
	at com.oracle.graal.python.nodes.control.ElseNode.executeVoid(ElseNode.java:51)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.ReturnTargetNode.execute(ReturnTargetNode.java:58)
	at com.oracle.graal.python.nodes.function.InnerRootNode.execute(InnerRootNode.java:66)
	at com.oracle.graal.python.nodes.function.FunctionRootNode.execute(FunctionRootNode.java:147)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:327)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:304)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:286)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:241)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNode.doNoClosure(CallTargetInvokeNode.java:117)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNode.doGeneric(CallTargetInvokeNode.java:125)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNodeGen.execute(CallTargetInvokeNodeGen.java:35)
	at com.oracle.graal.python.nodes.call.CallDispatchNode.callFunctionCachedCt(CallDispatchNode.java:103)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeCall(CallDispatchNodeGen.java:116)
	at com.oracle.graal.python.nodes.call.CallNode$CachedCallNode.functionCall(CallNode.java:171)
	at com.oracle.graal.python.nodes.call.CallNodeFactory$CachedCallNodeGen.execute(CallNodeFactory.java:106)
	at com.oracle.graal.python.nodes.call.PythonCallNode.call(PythonCallNode.java:279)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.execute(PythonCallNodeGen.java:59)
	at com.oracle.graal.python.nodes.expression.ExpressionNode$ExpressionStatementNode.executeVoid(ExpressionNode.java:131)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.ReturnTargetNode.execute(ReturnTargetNode.java:58)
	at com.oracle.graal.python.nodes.function.InnerRootNode.execute(InnerRootNode.java:66)
	at com.oracle.graal.python.nodes.function.FunctionRootNode.execute(FunctionRootNode.java:147)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:327)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:304)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:286)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:241)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNode.doNoClosure(CallTargetInvokeNode.java:117)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNode.doGeneric(CallTargetInvokeNode.java:125)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNodeGen.execute(CallTargetInvokeNodeGen.java:35)
	at com.oracle.graal.python.nodes.call.CallDispatchNode.callFunctionCachedCt(CallDispatchNode.java:103)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeCall(CallDispatchNodeGen.java:116)
	at com.oracle.graal.python.nodes.call.CallNode$CachedCallNode.functionCall(CallNode.java:171)
	at com.oracle.graal.python.nodes.call.CallNodeFactory$CachedCallNodeGen.execute(CallNodeFactory.java:106)
	at com.oracle.graal.python.nodes.call.PythonCallNode.call(PythonCallNode.java:279)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.execute(PythonCallNodeGen.java:59)
	at com.oracle.graal.python.nodes.frame.WriteLocalVariableNodeGen.executeVoid_generic4(WriteLocalVariableNodeGen.java:117)
	at com.oracle.graal.python.nodes.frame.WriteLocalVariableNodeGen.executeVoid(WriteLocalVariableNodeGen.java:50)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.ReturnTargetNode.execute(ReturnTargetNode.java:58)
	at com.oracle.graal.python.nodes.function.InnerRootNode.execute(InnerRootNode.java:66)
	at com.oracle.graal.python.nodes.function.FunctionRootNode.execute(FunctionRootNode.java:147)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:327)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:304)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:286)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:241)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNode.doNoClosure(CallTargetInvokeNode.java:117)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNode.doGeneric(CallTargetInvokeNode.java:125)
	at com.oracle.graal.python.nodes.call.CallTargetInvokeNodeGen.execute(CallTargetInvokeNodeGen.java:35)
	at com.oracle.graal.python.nodes.call.CallDispatchNode.callFunctionCachedCt(CallDispatchNode.java:103)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeCall(CallDispatchNodeGen.java:116)
	at com.oracle.graal.python.nodes.call.CallNode$CachedCallNode.functionCall(CallNode.java:171)
	at com.oracle.graal.python.nodes.call.CallNodeFactory$CachedCallNodeGen.executeAndSpecialize(CallNodeFactory.java:209)
	at com.oracle.graal.python.nodes.call.CallNodeFactory$CachedCallNodeGen.execute(CallNodeFactory.java:114)
	at com.oracle.graal.python.nodes.call.PythonCallNode.call(PythonCallNode.java:279)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.executeAndSpecialize(PythonCallNodeGen.java:91)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.execute(PythonCallNodeGen.java:63)
	at com.oracle.graal.python.nodes.frame.WriteNameNodeGen.executeVoid(WriteNameNodeGen.java:178)
	at com.oracle.graal.python.nodes.expression.ExpressionNode$ExpressionWithSideEffects.execute(ExpressionNode.java:192)
	at com.oracle.graal.python.nodes.function.InnerRootNode.execute(InnerRootNode.java:66)
	at com.oracle.graal.python.nodes.ModuleRootNode.execute(ModuleRootNode.java:72)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:327)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:317)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:304)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:286)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:229)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:216)
	at com.oracle.graal.python.builtins.Python3Core.loadFile(Python3Core.java:621)
	at com.oracle.graal.python.builtins.Python3Core.initializePythonCore(Python3Core.java:428)
	at com.oracle.graal.python.builtins.Python3Core.initialize(Python3Core.java:414)
	at com.oracle.graal.python.runtime.PythonContext.initialize(PythonContext.java:279)
	at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:204)
	at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:95)
	at com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:2352)
	at com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:195)
	at com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:521)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:802)
	at org.graalvm.polyglot.Context.eval(Context.java:344)
	at execution.table.MultithreadedTest.lambda$testPythonMultithread$0(MultithreadedTest.java:23)
	at java.lang.Thread.run(Thread.java:748)
Caused by: Attached Guest Language Frames (4)
```

**Comment by timfel** [comment]
Thank you for the report and the concise reproducer! We will look into it. One thing to try is to first initialize the first context, before starting the threads and running things in parallel.

**Comment by zolstein** [comment]
What do you mean by "initalize the first context before starting the threads"?
I tried adding the following lines just before creating the threads, and saw no change.
```java
Context firstContext = Context.newBuilder().engine(engine).build();
firstContext.eval(code).execute();
```

**Comment by msimacek** [comment]
We have identified race conditions in the AST and we'll be working on fixing them in the following weeks. As a workaround, avoid using engine sharing for now.

**Comment by zolstein** [comment]
Glad to see this get picked up. We needed to use engine sharing because our system needs to create many contexts, and initializing python on a fresh engine takes an _enormous_ amount of time and work. We found that by only sharing engines within a thread we could mitigate most of the issue, though it complicates some things we want to do.

**Comment by msimacek** [comment]
This and other race conditions that I was able to find shoud be fixed by https://github.com/graalvm/graalpython/commit/750d3616b2bb6081f250d99cf98cf37c8a60f2cb and https://github.com/graalvm/graalpython/commit/91f8c469ad5a41de1d1f26be4d67a13434775a11. Let me know if you encounter more problems.
