### ISSUE TITLE
strange error when install setuptools-scm

### ISSUE THREAD

**Issue by SchrodingerZhu** [graalvm/graalpython#114]
```
➜  lib proxychains4 -q /usr/lib/jvm/java-11-graalvm/bin/graalpython -m ginstall pypi setuptools_scm 
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   222  100   222    0     0    196      0  0:00:01  0:00:01 --:--:--   196
100  148k  100  148k    0     0  79315      0  0:00:01  0:00:01 --:--:--  265k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 36903  100 36903    0     0  50552      0 --:--:-- --:--:-- --:--:-- 50552
+ tar xzf /tmp/tmpfhas45mt/setuptools_scm-3.3.3.tar.gz -C /tmp/tmpfhas45mt
+ cd /tmp/tmpfhas45mt/setuptools_scm-3.3.3; CFLAGS="-v "  /usr/lib/jvm/java-11-graalvm/languages/python/bin/graalpython setup.py install --user 
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
running install
running bdist_egg
running egg_info
writing src/setuptools_scm.egg-info/PKG-INFO
writing dependency_links to src/setuptools_scm.egg-info/dependency_links.txt
writing entry points to src/setuptools_scm.egg-info/entry_points.txt
writing top-level names to src/setuptools_scm.egg-info/top_level.txt
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
Unexpected values provided for StartsWithNodeGen@6d36524e: [b'', (b']\x00\x00\x80', b'\xfd7zXZ'), NoValue, NoValue], [PBytes,PTuple,PNone,PNone]
Traceback (most recent call last):
  File "setup.py", line 118, in <module 'setup.py'>
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/__init__.py", line 145, in setup
  File "core.py", line 148, in setup
  File "dist.py", line 966, in run_commands
  File "dist.py", line 985, in run_command
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/install.py", line 67, in run
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/install.py", line 109, in do_egg_install
  File "cmd.py", line 313, in run_command
  File "dist.py", line 985, in run_command
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/bdist_egg.py", line 163, in run
  File "cmd.py", line 313, in run_command
  File "dist.py", line 985, in run_command
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/egg_info.py", line 296, in run
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/egg_info.py", line 303, in find_sources
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/egg_info.py", line 534, in run
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/egg_info.py", line 574, in add_defaults
  "/home/schrodinger/.local/lib/python3.7/site-packages/setuptools-42.0.2-py3.7.egg/setuptools/command/sdist.py", line 20, in walk_revctrl
  File "integration.py", line 27, in find_files
  File "file_finder_git.py", line 60, in git_find_files
  File "file_finder_git.py", line 49, in _git_ls_files_and_dirs
  File "file_finder_git.py", line 31, in _git_interpret_archive
  File "tarfile.py", line 1601, in open
  File "tarfile.py", line 357, in __init__
  File "tarfile.py", line 598, in getcomptype
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for StartsWithNodeGen@6d36524e: [b'', (b']\x00\x00\x80', b'\xfd7zXZ'), NoValue, NoValue], [PBytes,PTuple,PNone,PNone]
```

**Comment by timfel** [comment]
Thank you for the report. I think this is the same error that was described in #119

**Comment by zolstein** [comment]
This looks like a separate problem, but of the same kind. In https://github.com/graalvm/graalpython/issues/119 it couldn't find a specialization for bytes.find where start was a Long because it only expected an int. Here it can't find a specialization for bytes.startswith where prefix is a PTuple because it only expected a PIBytesLike. In this case we can probably solve the problem by making PTuple implement PIBytesLike; it already implements the getSequenceStorage method.
