### ISSUE TITLE
mx build error: Can't pickle local object 'build.<locals>.executeTask'

### ISSUE THREAD

**Issue by xqzhou** [graalvm/graalpython#153]
I'm getting the following error when trying to build graalpython, help is appreciated.

WARNING: No platform-specific definition is available for project com.oracle.truffle.llvm.tests.libc.native for your architecture (amd64)
JAVA_HOME: /Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home
16 unsatisfied dependencies were removed from build (use -v to list them)
23 non-default dependencies were removed from build (use -v to list them, mx build --all to build them)
Traceback (most recent call last):
  File "/Users/xq/Workspace/python/mx/mx.py", line 16994, in <module>
    main()
  File "/Users/xq/Workspace/python/mx/mx.py", line 16975, in main
    retcode = c(command_args)
  File "/Users/xq/Workspace/python/mx/mx_commands.py", line 147, in __call__
    return self.command_function(*args, **kwargs)
  File "/Users/xq/Workspace/python/mx/mx.py", line 13777, in build
    task.prepare(daemons)
  File "/Users/xq/Workspace/python/mx/mx.py", line 7135, in prepare
    self.compiler.prepare_daemon(daemons, self.compileArgs)
  File "/Users/xq/Workspace/python/mx/mx.py", line 7477, in prepare_daemon
    self.daemon = JavacDaemon(self.jdk, jvmArgs)
  File "/Users/xq/Workspace/python/mx/mx.py", line 7590, in __init__
    CompilerDaemon.__init__(self, jdk, jvmArgs, 'com.oracle.mxtool.compilerserver.JavacDaemon', jdk.toolsjar, ['--force-javac'])
  File "/Users/xq/Workspace/python/mx/mx.py", line 7490, in __init__
    build(buildArgs + ['--no-daemon', '--dependencies', 'com.oracle.mxtool.compilerserver'])
  File "/Users/xq/Workspace/python/mx/mx.py", line 13781, in build
    task.proc.start()
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'build.<locals>.executeTask'

**Comment by xqzhou** [comment]
set MX_PYTHON to 3.6 solved the issue
