### ISSUE TITLE
AttributeError: 'str' object has no attribute 'swapcase'

### ISSUE THREAD

**Issue by xqzhou** [graalvm/graalpython#154]
I'm trying to get Flask running and get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/importlib/_bootstrap.py", line 991, in _find_and_load
  File "/importlib/_bootstrap.py", line 671, in _load_unlocked
  File "/Users/xq/.local/lib/python3.8/site-packages/Flask-1.1.2-py3.8.egg/flask/__init__.py", line 14, in <module '__init__.py'>
    from jinja2 import escape
  File "/importlib/_bootstrap.py", line 991, in _find_and_load
  File "/importlib/_bootstrap.py", line 671, in _load_unlocked
  File "/Users/xq/.local/lib/python3.8/site-packages/Jinja2-2.11.2-py3.8.egg/jinja2/__init__.py", line 6, in <module '__init__.py'>
    from markupsafe import escape
  File "/importlib/_bootstrap.py", line 991, in _find_and_load
  File "/importlib/_bootstrap.py", line 671, in _load_unlocked
  File "/Users/xq/.local/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-macosx-10.14-x86_64.egg/markupsafe/__init__.py", line 31, in <module '__init__.py'>
    class Markup(text_type):
  File "/Users/xq/.local/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-macosx-10.14-x86_64.egg/markupsafe/__init__.py", line 202, in Markup
    locals()[method] = make_simple_escaping_wrapper(method)
  File "/Users/xq/.local/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-macosx-10.14-x86_64.egg/markupsafe/__init__.py", line 173, in make_simple_escaping_wrapper
    orig = getattr(text_type, name)
AttributeError: 'str' object has no attribute 'swapcase'

**Comment by timfel** [comment]
Thanks for the report, we will look into adding the missing methods. Be advised though that getting Flask to work is unlikely in the next year or so. Our sockets support is very basic, there is no SSL support and most socket options don't work properly, so even the built-in http server has very bad performance for us right now (about 10x - 100x slower than CPython). So unless you're doing a lot of computation for each request, this is going to be very slow
