### ISSUE TITLE
Is it presently possible to install pip and use python modules?

### ISSUE THREAD

**Issue by moxious** [graalvm/graalpython#16]
```
root@fe64b215f82d:/graalvm/jre/languages/python# curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1604k  100 1604k    0     0   415k      0  0:00:03  0:00:03 --:--:--  415k
root@fe64b215f82d:/graalvm/jre/languages/python# bin/graalpython get-pip.py 
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "get-pip.py", line 20651, in <module>
    main()
  File "get-pip.py", line 186, in main
    tmpdir = tempfile.mkdtemp()
  File "/graalvm/jre/languages/python/lib-python/3/tempfile.py", line 358, in mkdtemp
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/graalvm/jre/languages/python/lib-python/3/tempfile.py", line 130, in _sanitize_params
    dir = gettempdir()
  File "/graalvm/jre/languages/python/lib-python/3/tempfile.py", line 296, in gettempdir
    tempdir = _get_default_tempdir()
  File "/graalvm/jre/languages/python/lib-python/3/tempfile.py", line 205, in _get_default_tempdir
    name = next(namer)
  File "/graalvm/jre/languages/python/lib-python/3/tempfile.py", line 161, in _RandomNameSequence.__next__
    return ''.join(letters)
TypeError: sequence item 0: expected str instance, NotImplementedType found
root@fe64b215f82d:/graalvm/jre/languages/python# 

```

**Comment by timfel** [comment]
That's not possible at the moment. We will get to it eventually, but it's not the highest priority right now and many pieces are missing to make this work.

**Comment by oscarvarto** [comment]
@timfel hopefully using pip from graalpython is possible in the near future.

**Comment by BlankRain** [comment]
is it possible now?

**Comment by timfel** [comment]
It is possible (and pip is automatically installed when you create a venv), but since sockets are not implemented, you can only install packages after downloading them manually.




On Fri, May 24, 2019 at 5:35 AM +0200, "白小起" <notifications@github.com> wrote:












is it possible now?

**Comment by BlankRain** [comment]
thank you @timfel
