### ISSUE TITLE
External LLVMFunction _PyDict_GetItemStringWithError cannot be found

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#163]
I was curious if I could build numpy-1.19.2, so here's how I did it.
Build was successful by applying one minor patch. I still can't figure out what causes the error to load the shared library, though.

Build and install cython
-------------------------------
Download & extract cython from https://github.com/cython/cython/archive/0.29.21.tar.gz

```
graalpython ./setup.py install --user
```

Build and install numpy
-------------------------------
Download & extract numpy from https://github.com/numpy/numpy/releases/download/v1.19.2/numpy-1.19.2.tar.gz

We are unable to compile numpy-1.19.2 as is, yet:

```
numpy/core/src/multiarray/typeinfo.c:104:5: error: static declaration of 'PyStructSequence_InitType2' follows non-static declaration
    PyStructSequence_InitType2(PyTypeObject *type, PyStructSequence_Desc *desc) {
    ^
/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_9EE94B73E5_JAVA11/graalvm-9ee94b73e5-java11-20.3.0-dev/languages/python/include/structseq.h:32:17: note: previous declaration is here
PyAPI_FUNC(int) PyStructSequence_InitType2(PyTypeObject *type,
                ^
1 warning and 1 error generated.
error: Command "/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_9EE94B73E5_JAVA11/graalvm-9ee94b73e5-java11-20.3.0-dev/languages/llvm/native/bin/graalvm-native-clang -Wno-unused-command-line-argument -stdlib=libc++ -DNDEBUG -O1 -DHPY_UNIVERSAL_ABI -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DHAVE_CBLAS -I/home/ryuta/local/include/blis -Ibuild/src.linux-x86_64-3.8/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.8/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_9EE94B73E5_JAVA11/graalvm-9ee94b73e5-java11-20.3.0-dev/languages/python/include -Ibuild/src.linux-x86_64-3.8/numpy/core/src/common -Ibuild/src.linux-x86_64-3.8/numpy/core/src/npymath -c numpy/core/src/multiarray/typeinfo.c -o build/temp.linux-x86_64-3.8/numpy/core/src/multiarray/typeinfo.o -MMD -MF build/temp.linux-x86_64-3.8/numpy/core/src/multiarray/typeinfo.o.d" failed with exit status 1
```

This seems to be caused by the preprocessing for older pypy compatibility.
To fix the compilation error, modify

```
numpy-1.19.2/numpy/core/src/multiarray/typeinfo.c
```

such that

```
102c102
< #if (defined(PYPY_VERSION_NUM) && (PYPY_VERSION_NUM < 0x07020000))
---
> #if (PY_VERSION_HEX < 0x03040000)
```

Make sure to build numpy by serial, otherwise graalpython crashes due to the bug in multiprocessing module.

```
NPY_NUM_BUILD_JOBS=1 graalpython ./setup.py install --user
```

Importing NumPy
-----------------------
```
graalpython -c "import numpy"
```

Unfortunately, import fails with `External LLVMFunction _PyDict_GetItemStringWithError cannot be found.`

Here's more detailed message:

```
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg/numpy/core/__init__.py", line 22, in <module '__init__.py'>
    from . import multiarray
ImportError: cannot load /home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg/numpy/core/_multiarray_umath.graalpython-native-x86_64-linux.so: External LLVMFunction _PyDict_GetItemStringWithError cannot be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg/numpy/core/__init__.py", line 48, in <module '__init__.py'>
    raise ImportError(msg)
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.8 from "/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_9EE94B73E5_JAVA11/graalvm-9ee94b73e5-java11-20.3.0-dev/languages/python/bin/graalpython"
  * The NumPy version is: "1.19.2"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: cannot load /home/ryuta/.local/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg/numpy/core/_multiarray_umath.graalpython-native-x86_64-linux.so: External LLVMFunction _PyDict_GetItemStringWithError cannot be found.
```

**Comment by msimacek** [comment]
The link error is because the function is really missing on our side. We try to implement all the functions from the CPython stable API, but this function is not part of it (prefixed by underscore). For such functions, we implement them on as-needed basis, so I'll add it now.
