### ISSUE TITLE
KeyError: __subclasshook__

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#165]
I've got the following error while importing jedi

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/u/cd4mcq/.local/lib/python3.8/site-packages/jedi-0.0.0-py3.8.egg/jedi/inference/compiled/access.py", line 47, in <module '/u/cd4mcq/.local/lib/python3.8/site-packages/jedi-0.0.0-py3.8.egg/jedi/inference/compiled/access.py'>
    ClassMethodDescriptorType = type(object_class_dict['__subclasshook__'])
KeyError: __subclasshook__
```

Here's how to reproduce error:

```
graalpython -m ginstall pypi parso
graalpython -m ginstall pypi jedi
graalpython -c "import jedi"
```

**Comment by oroppas** [comment]
CPython
```
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> type.__dict__['__dict__'].__get__(object)
mappingproxy({'__repr__': <slot wrapper '__repr__' of 'object' objects>, '__hash__': <slot wrapper '__hash__' of 'object' objects>, '__str__': <slot wrapper '__str__' of 'object' objects>, '__getattribute__': <slot wrapper '__getattribute__' of 'object' objects>, '__setattr__': <slot wrapper '__setattr__' of 'object' objects>, '__delattr__': <slot wrapper '__delattr__' of 'object' objects>, '__lt__': <slot wrapper '__lt__' of 'object' objects>, '__le__': <slot wrapper '__le__' of 'object' objects>, '__eq__': <slot wrapper '__eq__' of 'object' objects>, '__ne__': <slot wrapper '__ne__' of 'object' objects>, '__gt__': <slot wrapper '__gt__' of 'object' objects>, '__ge__': <slot wrapper '__ge__' of 'object' objects>, '__init__': <slot wrapper '__init__' of 'object' objects>, '__new__': <built-in method __new__ of type object at 0x56493522ac60>, '__reduce_ex__': <method '__reduce_ex__' of 'object' objects>, '__reduce__': <method '__reduce__' of 'object' objects>, '__subclasshook__': <method '__subclasshook__' of 'object' objects>, '__init_subclass__': <method '__init_subclass__' of 'object' objects>, '__format__': <method '__format__' of 'object' objects>, '__sizeof__': <method '__sizeof__' of 'object' objects>, '__dir__': <method '__dir__' of 'object' objects>, '__class__': <attribute '__class__' of 'object' objects>, '__doc__': 'The base class of the class hierarchy.\n\nWhen called, it accepts no arguments and returns a new featureless\ninstance that has no instance attributes and cannot be given any.\n'})
>>> object_class_dict = type.__dict__['__dict__'].__get__(object)
>>> type(object_class_dict['__subclasshook__'])
<class 'classmethod_descriptor'>
```

GraalPython
```
Python 3.8.5 (Sat Oct 24 15:36:10 JST 2020)
[Graal, GraalVM CE, Java 11.0.8] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> type.__dict__['__dict__'].__get__(object)
mappingproxy({'__doc__': None, '__new__': <method '__new__' of 'object' objects>, '__lt__': <method '__lt__' of 'object' objects>, '__str__': <method '__str__' of 'object' objects>, '__getattribute__': <method '__getattribute__' of 'object' objects>, '__hash__': <method '__hash__' of 'object' objects>, '__eq__': <method '__eq__' of 'object' objects>, '__gt__': <method '__gt__' of 'object' objects>, '__delattr__': <method '__delattr__' of 'object' objects>, '__class__': <attribute '__class__' of 'object' objects>, '__init_subclass__': <classmethod object at 0x6a83c669>, '__le__': <method '__le__' of 'object' objects>, '__setattr__': <method '__setattr__' of 'object' objects>, '__ge__': <method '__ge__' of 'object' objects>, '__repr__': <method '__repr__' of 'object' objects>, '__init__': <method '__init__' of 'object' objects>, '__truffle_richcompare__': <method '__truffle_richcompare__' of 'object' objects>, '__ne__': <method '__ne__' of 'object' objects>, '__format__': <method '__format__' of 'object' objects>, '__reduce__': <function __reduce__ at 0x5a97e8c5>, '__reduce_ex__': <function __reduce_ex__ at 0x52c86eba>, '__sizeof__': <function __sizeof__ at 0x276a03dd>, '__dir__': <function __dir__ at 0x74df953e>})
>>> object_class_dict = type.__dict__['__dict__'].__get__(object)
>>> type(object_class_dict['__subclasshook__'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: __subclasshook__
```
