### ISSUE TITLE
[ast] literal_eval fails with malformed node or string

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#169]
**CPython**
```python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.literal_eval("{'a': {'b':'c'}}")
{'a': {'b': 'c'}}
```
**GraalPython**
```python
Python 3.8.5 (Fri Oct 30 11:33:35 JST 2020)
[Graal, GraalVM CE, Java 11.0.8] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.literal_eval("{'a': {'b':'c'}}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 98, in _convert
    return _convert_signed_num(node)
  File "/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 75, in _convert_signed_num
    return _convert_num(node)
  File "/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 66, in _convert_num
    _raise_malformed_node(node)
  File "/home/ryuta/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 63, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <code object <unknown>, file "<unknown>", line 1>
```

**Comment by timfel** [comment]
The `ast` module is not currently supported. We do not currently planned to work on it, since it exposes internals of the Python parser that we do not implement and would like to avoid supporting. Is there a reason you cannot just use `compile`/`exec`/`eval`?

**Comment by oroppas** [comment]
Thank you for the comment, @timfel. I understand `ast` is not currently supported and the priority is low.
I was going to use `parso`, which by the way, ultimately is required by `ipython` through `jedi`

```python
graalpython -c "import parso; grammer38 = parso.load_grammar(version='3.8')"
Traceback (most recent call last):
  File "/u/cd4mcq/.local/lib/python3.8/site-packages/parso-0.8.0-py3.8.egg/parso/grammar.py", line 252, in load_grammar
    return _loaded_grammars[path]
KeyError: /u/cd4mcq/.local/lib/python3.8/site-packages/parso-0.8.0-py3.8.egg/parso/python/grammar38.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/u/cd4mcq/.local/lib/python3.8/site-packages/parso-0.8.0-py3.8.egg/parso/grammar.py", line 258, in load_grammar
    grammar = PythonGrammar(version_info, bnf_text)
  File "/u/cd4mcq/.local/lib/python3.8/site-packages/parso-0.8.0-py3.8.egg/parso/grammar.py", line 218, in __init__
    super().__init__(
  File "/u/cd4mcq/.local/lib/python3.8/site-packages/parso-0.8.0-py3.8.egg/parso/grammar.py", line 40, in __init__
    self._pgen_grammar = generate_grammar(
  File "/u/cd4mcq/.local/lib/python3.8/site-packages/parso-0.8.0-py3.8.egg/parso/pgen2/generator.py", line 271, in generate_grammar
    transition = _make_transition(
  File "/u/cd4mcq/.local/lib/python3.8/site-packages/parso-0.8.0-py3.8.egg/parso/pgen2/generator.py", line 294, in _make_transition
    value = literal_eval(label)
  File "/u/cd4mcq/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 99, in literal_eval
    return _convert(node_or_string)
  File "/u/cd4mcq/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 98, in _convert
    return _convert_signed_num(node)
  File "/u/cd4mcq/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 75, in _convert_signed_num
    return _convert_num(node)
  File "/u/cd4mcq/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 66, in _convert_num
    _raise_malformed_node(node)
  File "/u/cd4mcq/packages/graal/graal/sdk/mxbuild/linux-amd64/GRAALVM_3903C82821_JAVA11/graalvm-3903c82821-java11-21.0.0-dev/languages/python/lib-python/3/ast.py", line 63, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <code object <unknown>, file "<unknown>", line 1>
```

**Comment by timfel** [comment]
Indeed, eventually we will have to support it. In the mean time, our approach is to use things like the GraalVM LSP server and other polyglot solutions that will cover Python as well for debugging, code completion, live programming and other IDE and development-time interactions.

**Comment by timfel** [comment]
I am going to close this issue, since this very likely won't happen in 2021 either.

**Comment by msimacek** [comment]
We now support the `ast` module
