### ISSUE TITLE
Problem with using the uuid module

### ISSUE THREAD

**Issue by antonpenev** [graalvm/graalpython#19]
Hi, when I try to make a simple test script for general uuid generating like:
```
import uuid
print('id ', str(uuid.uuid4()))
```
When I run with graalpython, I have the following exception: 
```
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import uuid
  File "_bootstrap.py", line 1074, in __import__
  File "_bootstrap.py", line 994, in _gcd_import
  File "_bootstrap.py", line 971, in _find_and_load
  File "_bootstrap.py", line 955, in _find_and_load_unlocked
  File "_bootstrap.py", line 665, in _load_unlocked
  File "_bootstrap_external.py", line 681, in _LoaderBasics.exec_module
  File "_bootstrap.py", line 219, in _call_with_frames_removed
  File "functions.py", line 123, in exec
  File "/opt/graalvm/jre/languages/python/lib-python/3/uuid.py", line 633, in <module>
    NAMESPACE_DNS = UUID('6ba7b810-9dad-11d1-80b4-00c04fd430c8')
  File "/opt/graalvm/jre/languages/python/lib-python/3/uuid.py", line 141, in UUID.__init__
    int = int_(hex, 16)
ValueError: invalid literal for int() with base 16: 6ba7b8109dad11d180b400c04fd430c8
)
```
*OS*: Ubuntu 18.04
*GraalVM version*: graalvm-ce-1.0.0-rc6

**Comment by lukasstadler** [comment]
Hi Anton,
the base gets lost in our parsing code so that it tries (and fails) with a base of 10.
Thanks for the report, this will be fixed soon.
- Lukas

**Comment by lukasstadler** [comment]
should be fixed with https://github.com/graalvm/graalpython/commit/bea43548cde23eb5a6a944babc1798e275ec490d, and will land with the next binary release.
