### ISSUE TITLE
Python can not interpret float, char, short and byte types in a Java object

### ISSUE THREAD

**Issue by reals1987** [graalvm/graalpython#22]
I'd like to pass a Java object to a python function, however, some types can not be interpreted in type char, short, float and byte.
Here is my Java code, two classes
HelloPolyglot: get an object from a python file, and pass a Java object to one of its function
JavaObject: the Java object to be passed
-----------------------------------------------------
```
import org.graalvm.polyglot.*;
import org.graalvm.polyglot.proxy.*;
import java.io.File;

public class HelloPolyglot {
    public static void main(String[] args) throws Exception {
    	JavaObject order = new JavaObject();
    	object.setStrategyId("strategyIdxx");
    	object.setCumAmount(1000d);
        object.setByteValue((byte)127);
        object.setShortValue((short)32767);
        object.setIntValue(2_147_483_647);
        object.setLongValue(9_223_372_036_854_775_807L);
        object.setFloatValue(0);
        object.setDoubleValue(2000d);
        object.setBooleanValue(true);
        object.setCharValue('a');

    	File file = new File("/home/appadmin/graalvm/script", "polyglot_example.py");
		String language = Source.findLanguage(file);

		Context context = Context.newBuilder(language)
            .allowAllAccess(false)
            .allowHostAccess(false)
            .allowHostClassLoading(false)
            .allowIO(true)
            .allowNativeAccess(false)
            .allowCreateThread(false)               
            .build();
        Value v = context.getPolyglotBindings();
		Source source = Source.newBuilder(language, file).build();
		context.eval(source);
		Value main = context.getPolyglotBindings().getMember("foo");		
		Value instance = main.execute();
		Value onNewOrderRejected = instance.getMember("onNewOrderRejected");
		onNewOrderRejected.execute(object);
		context.close();
    }
}
```

------------------------------------------------------------------
```
public class JavaObject {
    private byte byteValue;
    private short shortValue;
    private int intValue;
    private long longValue;
    private float floatValue;
    private double doubleValue;
    private boolean booleanValue;
    public char charValue;

    public byte getByteValue() {
        return byteValue;
    }

    public void setByteValue(byte byteValue) {
        this.byteValue = byteValue;
    }

    public short getShortValue() {
        return shortValue;
    }

    public void setShortValue(short shortValue) {
        this.shortValue = shortValue;
    }

    public Integer getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }

    public long getLongValue() {
        return longValue;
    }

    public void setLongValue(long longValue) {
        this.longValue = longValue;
    }

    public float getFloatValue() {
        return floatValue;
    }

    public void setFloatValue(float floatValue) {
        this.floatValue = floatValue;
    }

    public double getDoubleValue() {
        return doubleValue;
    }

    public void setDoubleValue(double doubleValue) {
        this.doubleValue = doubleValue;
    }

    public boolean isBooleanValue() {
        return booleanValue;
    }

    public void setBooleanValue(boolean booleanValue) {
        this.booleanValue = booleanValue;
    }

    public Character getCharValue() {
        return 'a';
    }

    public void setCharValue(char charValue) {
        this.charValue = charValue;
    }
}
```
----------------------------------------------------------------------
```
#!/usr/bin/python
# -*- coding: UTF-8 -*-
import polyglot
import java

@polyglot.export_value
def foo():
	return PythonStrategy()

class PythonStrategy:

	def onNewOrderRejected(self, order):
		print(order.getIntValue())
		print(order.getLongValue())
		print(order.getDoubleValue())		
		print(order.isBooleanValue())	
		# print(order.getByteValue())  # error
		# print(order.getShortValue()) # error
		# print(order.getFloatValue()) # error
		# print(order.getCharValue()) # error
		return

```
-----------------------------------------------
I got the following exception for byte, short, float and char type:
Exception in thread "main" org.graalvm.polyglot.PolyglotException: com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for GetClassNodeGen@650ae78c: [234.5], [Float]
	at com.oracle.graal.python.nodes.object.GetClassNodeGen.executeAndSpecialize(GetClassNodeGen.java:531)
	at com.oracle.graal.python.nodes.object.GetClassNodeGen.executeGetClass(GetClassNodeGen.java:216)
	at com.oracle.graal.python.nodes.object.GetClassNode.execute(GetClassNode.java:86)
	at com.oracle.graal.python.nodes.attributes.LookupInheritedAttributeNode.execute(LookupInheritedAttributeNode.java:74)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNode.callObject(LookupAndCallUnaryNode.java:204)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeAndSpecialize(LookupAndCallUnaryNodeGen.java:801)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeDouble(LookupAndCallUnaryNodeGen.java:416)
	at com.oracle.graal.python.builtins.modules.BuiltinConstructors$FloatNode.doubleFromObject(BuiltinConstructors.java:680)
	at com.oracle.graal.python.builtins.modules.BuiltinConstructorsFactory$FloatNodeFactory$FloatNodeGen.executeAndSpecialize(BuiltinConstructorsFactory.java:1774)
	at com.oracle.graal.python.builtins.modules.BuiltinConstructorsFactory$FloatNodeFactory$FloatNodeGen.execute(BuiltinConstructorsFactory.java:1693)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode$BuiltinAnyCallNode.execute(BuiltinFunctionRootNode.java:72)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode.execute(BuiltinFunctionRootNode.java:266)
	at <python> float(Unknown)
	at <python> PythonStrategy.onNewOrderRejected(polyglot_example.py:36:723-750)
	at org.graalvm.polyglot.Value.execute(Value.java:338)
	at HelloPolyglot.main(HelloPolyglot.java:54)
Original Internal Error: 
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Unexpected values provided for GetClassNodeGen@650ae78c: [234.5], [Float]
	at com.oracle.graal.python.nodes.object.GetClassNodeGen.executeAndSpecialize(GetClassNodeGen.java:531)
	at com.oracle.graal.python.nodes.object.GetClassNodeGen.executeGetClass(GetClassNodeGen.java:216)
	at com.oracle.graal.python.nodes.object.GetClassNode.execute(GetClassNode.java:86)
	at com.oracle.graal.python.nodes.attributes.LookupInheritedAttributeNode.execute(LookupInheritedAttributeNode.java:74)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNode.callObject(LookupAndCallUnaryNode.java:204)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeAndSpecialize(LookupAndCallUnaryNodeGen.java:801)
	at com.oracle.graal.python.nodes.call.special.LookupAndCallUnaryNodeGen.executeDouble(LookupAndCallUnaryNodeGen.java:416)
	at com.oracle.graal.python.builtins.modules.BuiltinConstructors$FloatNode.doubleFromObject(BuiltinConstructors.java:680)
	at com.oracle.graal.python.builtins.modules.BuiltinConstructorsFactory$FloatNodeFactory$FloatNodeGen.executeAndSpecialize(BuiltinConstructorsFactory.java:1774)
	at com.oracle.graal.python.builtins.modules.BuiltinConstructorsFactory$FloatNodeFactory$FloatNodeGen.execute(BuiltinConstructorsFactory.java:1693)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode$BuiltinAnyCallNode.execute(BuiltinFunctionRootNode.java:72)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode.execute(BuiltinFunctionRootNode.java:266)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:285)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:274)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:264)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:246)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:229)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
	at com.oracle.graal.python.nodes.call.InvokeNode.doNoKeywords(InvokeNode.java:244)
	at com.oracle.graal.python.nodes.call.InvokeNodeGen.executeAndSpecialize(InvokeNodeGen.java:61)
	at com.oracle.graal.python.nodes.call.InvokeNodeGen.execute(InvokeNodeGen.java:48)
	at com.oracle.graal.python.nodes.call.CallDispatchNode.callFunction(CallDispatchNode.java:106)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeAndSpecialize(CallDispatchNodeGen.java:315)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeCall(CallDispatchNodeGen.java:139)
	at com.oracle.graal.python.nodes.call.CallNode.builtinFunctionCall(CallNode.java:126)
	at com.oracle.graal.python.nodes.call.CallNodeGen.executeAndSpecialize(CallNodeGen.java:102)
	at com.oracle.graal.python.nodes.call.CallNodeGen.execute(CallNodeGen.java:59)
	at com.oracle.graal.python.nodes.call.special.CallVarargsMethodNode.call(CallVarargsMethodNode.java:126)
	at com.oracle.graal.python.nodes.call.special.CallVarargsMethodNodeGen.executeAndSpecialize(CallVarargsMethodNodeGen.java:523)
	at com.oracle.graal.python.nodes.call.special.CallVarargsMethodNodeGen.execute(CallVarargsMethodNodeGen.java:184)
	at com.oracle.graal.python.builtins.objects.type.TypeBuiltins$CallNode.op(TypeBuiltins.java:190)
	at com.oracle.graal.python.builtins.objects.type.TypeBuiltins$CallNode.doItUnboxed(TypeBuiltins.java:165)
	at com.oracle.graal.python.builtins.objects.type.TypeBuiltinsFactory$CallNodeFactory$CallNodeGen.executeAndSpecialize(TypeBuiltinsFactory.java:510)
	at com.oracle.graal.python.builtins.objects.type.TypeBuiltinsFactory$CallNodeFactory$CallNodeGen.execute(TypeBuiltinsFactory.java:469)
	at com.oracle.graal.python.builtins.objects.type.TypeBuiltins$CallNode.varArgExecute(TypeBuiltins.java:155)
	at com.oracle.graal.python.nodes.call.special.CallVarargsMethodNode.call(CallVarargsMethodNode.java:68)
	at com.oracle.graal.python.nodes.call.special.CallVarargsMethodNodeGen.executeAndSpecialize(CallVarargsMethodNodeGen.java:234)
	at com.oracle.graal.python.nodes.call.special.CallVarargsMethodNodeGen.execute(CallVarargsMethodNodeGen.java:184)
	at com.oracle.graal.python.nodes.call.CallNode.specialCall(CallNode.java:90)
	at com.oracle.graal.python.nodes.call.CallNodeGen.executeAndSpecialize(CallNodeGen.java:74)
	at com.oracle.graal.python.nodes.call.CallNodeGen.execute(CallNodeGen.java:59)
	at com.oracle.graal.python.nodes.call.PythonCallNode.call(PythonCallNode.java:261)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.executeAndSpecialize(PythonCallNodeGen.java:82)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.execute(PythonCallNodeGen.java:55)
	at com.oracle.graal.python.nodes.argument.positional.PositionalArgumentsNode.evaluateArguments(PositionalArgumentsNode.java:78)
	at com.oracle.graal.python.nodes.call.PythonCallNode.evaluateArguments(PythonCallNode.java:216)
	at com.oracle.graal.python.nodes.call.PythonCallNode.call(PythonCallNode.java:259)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.executeAndSpecialize(PythonCallNodeGen.java:82)
	at com.oracle.graal.python.nodes.call.PythonCallNodeGen.execute(PythonCallNodeGen.java:55)
	at com.oracle.graal.python.nodes.expression.ExpressionNode$ExpressionStatementNode.executeVoid(ExpressionNode.java:117)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.BlockNode.executeVoid(BlockNode.java:54)
	at com.oracle.graal.python.nodes.control.ReturnTargetNode.execute(ReturnTargetNode.java:58)
	at com.oracle.graal.python.nodes.function.FunctionRootNode.execute(FunctionRootNode.java:142)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:285)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:274)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:264)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:246)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:229)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
	at com.oracle.graal.python.nodes.call.InvokeNode.doNoKeywords(InvokeNode.java:244)
	at com.oracle.graal.python.nodes.call.InvokeNodeGen.executeAndSpecialize(InvokeNodeGen.java:61)
	at com.oracle.graal.python.nodes.call.InvokeNodeGen.execute(InvokeNodeGen.java:48)
	at com.oracle.graal.python.nodes.call.CallDispatchNode.callMethod(CallDispatchNode.java:74)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeAndSpecialize(CallDispatchNodeGen.java:184)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeCall(CallDispatchNodeGen.java:139)
	at com.oracle.graal.python.nodes.call.CallNode.methodCall(CallNode.java:111)
	at com.oracle.graal.python.nodes.call.CallNodeGen.executeAndSpecialize(CallNodeGen.java:81)
	at com.oracle.graal.python.nodes.call.CallNodeGen.execute(CallNodeGen.java:59)
	at com.oracle.graal.python.runtime.interop.PythonMessageResolution$ExecuteNode.doCall(PythonMessageResolution.java:303)
	at com.oracle.graal.python.runtime.interop.PythonMessageResolution$ExecuteNode.execute(PythonMessageResolution.java:298)
	at com.oracle.graal.python.runtime.interop.PythonMessageResolution$PForeignFunctionExecuteNode.access(PythonMessageResolution.java:430)
	at com.oracle.graal.python.runtime.interop.PythonMessageResolutionForeign$PForeignFunctionExecuteSubNode.accessWithTarget(PythonMessageResolutionForeign.java:122)
	at com.oracle.graal.python.runtime.interop.PythonMessageResolutionForeignFactory$PForeignFunctionExecuteSubNodeGen.executeAndSpecialize(PythonMessageResolutionForeignFactory.java:65)
	at com.oracle.graal.python.runtime.interop.PythonMessageResolutionForeignFactory$PForeignFunctionExecuteSubNodeGen.executeWithTarget(PythonMessageResolutionForeignFactory.java:51)
	at com.oracle.graal.python.runtime.interop.PythonMessageResolutionForeign$PForeignFunctionExecuteSubNode$EXECUTERootNode.execute(PythonMessageResolutionForeign.java:144)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:285)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:274)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:264)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:246)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:229)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.callProxy(OptimizedDirectCallNode.java:88)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:72)
	at com.oracle.truffle.api.interop.InteropAccessNode.doCached(InteropAccessNode.java:202)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeAndSpecialize(InteropAccessNodeGen.java:82)
	at com.oracle.truffle.api.interop.InteropAccessNodeGen.executeImpl(InteropAccessNodeGen.java:45)
	at com.oracle.truffle.api.interop.InteropAccessNode.execute(InteropAccessNode.java:83)
	at com.oracle.truffle.api.interop.ForeignAccess.sendExecute(ForeignAccess.java:436)
	at com.oracle.truffle.polyglot.PolyglotValue$Interop$AbstractExecuteNode.executeShared(PolyglotValue.java:2146)
	at com.oracle.truffle.polyglot.PolyglotValue$Interop$ExecuteNode.executeImpl(PolyglotValue.java:2226)
	at com.oracle.truffle.polyglot.PolyglotValue$PolyglotNode.execute(PolyglotValue.java:529)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:285)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:274)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:264)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:246)
	at org.graalvm.compiler.truffle.runtime.GraalTVMCI.callProfiled(GraalTVMCI.java:86)
	at com.oracle.truffle.api.impl.Accessor.callProfiled(Accessor.java:718)
	at com.oracle.truffle.polyglot.VMAccessor.callProfiled(VMAccessor.java:91)
	at com.oracle.truffle.polyglot.PolyglotValue$Interop.execute(PolyglotValue.java:1388)
	at org.graalvm.polyglot.Value.execute(Value.java:338)
	at HelloPolyglot.main(HelloPolyglot.java:54)
Caused by: Attached Guest Language Frames (4)

**Comment by timfel** [comment]
You are right, we don't support these primitive types, yet. We'll work on this.

**Comment by timfel** [comment]
The fix for this should be included in the next release

**Comment by timfel** [comment]
Fix was released with rc8
