### ISSUE TITLE
Recover from Exception, not die with segmentation fault

### ISSUE THREAD

**Issue by TisonKun** [graalvm/graalpython#3]
```
➜  ~ graalpython
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> 1 / 0
[1]    3747 segmentation fault  graalpython
➜  ~ python
Python 3.6.5 (default, Mar 30 2018, 06:42:10) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 1 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>>
```

**Comment by W4anD0eR96** [comment]
The original case I stuck with is:
```
➜  ~ graalpython
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> class A:
...   def __init__(self, n):
...     self.n = n
...   def get_value():
...     return self.n
... 
>>> A(42).get_value()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: get_value() takes no arguments (1 given)
>>> [1]    3044 segmentation fault  graalpython
```

**Comment by timfel** [comment]
Can you try running the same with `graalpython --jvm`? You might be running into a known issue with the aot-compiled version of Python. If that is the case, we have a fix that'll be in RC2

**Comment by thedrow** [comment]
rc2 is released so this can be closed no?

**Comment by TisonKun** [comment]
... close as verified
