### ISSUE TITLE
`typing` is broken

### ISSUE THREAD

**Issue by KOLANICH** [graalvm/graalpython#47]
```python
import typing
```
raises

**Comment by cosminbasca** [comment]
Hi @KOLANICH, are you still getting the error?  Importing  `typing`  seems to work fine on the current tip. So does this simple code snipped:
```python
from typing import NewType

UserId = NewType('UserId', int)
some_id = UserId(524313)
print(some_id)
```
however, type hints are not yet supported by our parser, see GH-38.

**Comment by KOLANICH** [comment]
> Importing typing seems to work fine on the current tip.

I use the prebuilt releases, so cannot check `master`.

**Comment by timfel** [comment]
The fix is included in the rc12 above example works in the rc12 release.

**Comment by KOLANICH** [comment]
Works. Thank you.

**Comment by oroppas** [comment]
I got the error importing `typing` when installing chainer (https://github.com/chainer/chainer)

```python
>>> import typing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module '<expression>'>
  File "_bootstrap.py", line 1086, in __import__
  File "_bootstrap.py", line 1006, in _gcd_import
  File "_bootstrap.py", line 983, in _find_and_load
  File "_bootstrap.py", line 967, in _find_and_load_unlocked
  File "_bootstrap.py", line 677, in _load_unlocked
  File "_bootstrap_external.py", line 731, in exec_module
  File "_bootstrap.py", line 219, in _call_with_frames_removed
  File "typing.py", line 1174, in <module 'typing.py'>
    T = TypeVar('T')  # Any type.
TypeError: '_ProtocolMeta' object is not subscriptable
```

**Comment by timfel** [comment]
@oroppas which version is this? it should work fine since rc12 and on master

**Comment by oroppas** [comment]
it's the master branch

**Comment by KOLANICH** [comment]
I confirm, it is really broken in the latest release.
