### ISSUE TITLE
Pandas import is not working proprely

### ISSUE THREAD

**Issue by crakjie** [graalvm/graalpython#55]
With graalvm RC12 I got following error while importing pandas in graalpython repl.

On Ubuntu 16.04 with clang-7

```
~/workspace/polyglot$ /usr/lib/jvm/graalvm-ce-1.0.0-rc12/bin/graalpython
Python 3.7.0 (Fri Feb 01 11:43:57 UTC 2019)
[GraalVM CE, Java 1.8.0_192] on linux
Type "help", "copyright", "credits" or "license" for more information.
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 1074, in __import__
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 994, in _gcd_import
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 971, in _find_and_load
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 955, in _find_and_load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 665, in _load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap_external.py", line 681, in exec_module
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 219, in _call_with_frames_removed
  File "/home/etienne/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/__init__.py", line 58, in <module>
    from pandas.io.api import *
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 1074, in __import__
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 994, in _gcd_import
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 971, in _find_and_load
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 955, in _find_and_load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 665, in _load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap_external.py", line 681, in exec_module
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 219, in _call_with_frames_removed
  File "/home/etienne/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/api.py", line 18, in <module>
    from pandas.io.packers import read_msgpack, to_msgpack
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 1074, in __import__
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 994, in _gcd_import
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 971, in _find_and_load
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 955, in _find_and_load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 665, in _load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap_external.py", line 681, in exec_module
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 219, in _call_with_frames_removed
  File "/home/etienne/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/packers.py", line 68, in <module>
    from pandas.io.msgpack import Unpacker as _Unpacker, Packer as _Packer, ExtType
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 1074, in __import__
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 994, in _gcd_import
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 971, in _find_and_load
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 955, in _find_and_load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 665, in _load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap_external.py", line 681, in exec_module
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 219, in _call_with_frames_removed
  File "/home/etienne/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/msgpack/__init__.py", line 9, in <module>
    class ExtType(namedtuple('ExtType', 'code data')):
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 1074, in __import__
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 994, in _gcd_import
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 971, in _find_and_load
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pandas.io.msgpack._packer'
```

If a try to import a second time I got this error :
```
>>> import pandas as pd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 1074, in __import__
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 994, in _gcd_import
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 971, in _find_and_load
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 955, in _find_and_load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 665, in _load_unlocked
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap_external.py", line 681, in exec_module
  File "/b/b/e/graalpython/graalpython/lib-python/3/importlib/_bootstrap.py", line 219, in _call_with_frames_removed
  File "/home/etienne/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/__init__.py", line 51, in <module>
    plot_params = pandas.plotting._style._Options(deprecated=True)
AttributeError: 'module' object has no attribute 'plotting'
```

I'm also wondering why it's so slow to do imports, numpy take something like 30s to be imported in the graalpython repl.

**Comment by fangerer** [comment]
Hi Crakjie,
thanks for reporting this issue. Unfortunately, I could not reproduce this problem with RC12. I assume the problem is that you are using LLVM 7. Please refer to our `README.md` where we recommend using LLVM 6.
Since you are using Ubuntu, I recommend to install LLVM 6 as an alternative. Then you can easily switch between LLVM 6 and 7. It should be sufficient to switch to LLVM 6 just for installing Numpy and Pandas.

The reason why importing Numpy and Pandas takes several seconds is because of the nature of our system. Just importing the packages already causes large amounts of C code to be executed. But in contrast to CPython, we are not running AOT compiled C code but we are compiling just-in-time.
We are aware of this drawback and working on a solution but that will take some more time.

**Comment by crakjie** [comment]
Hello Florian,
I installed clang-6 and link clang, clang++, llvm-link, llvm-extract, llvm-nm, and opt as alternative.
Uninstall all python module with graalpython. And then reinstall numpy and pandas module.
I still have the same error.

**Comment by crakjie** [comment]
While scrolling the pandas compilation log I saw an error that may be related.
```
building 'pandas.io.msgpack._unpacker' extension
/usr/lib/jvm/graalvm-ce-1.0.0-rc12/jre/languages/python/bin/graalpython -CC -DNDEBUG -O1 -allowcpp -fPIC -D__LITTLE_ENDIAN__=1 -Ipandas/_libs/src/msgpack -Ipandas/_libs/src/klib -Ipandas/_libs/src -I/home/etienne/.local/lib/python3.7/site-packages/numpy-1.14.3-py3.7-linux-x86_64.egg/numpy/core/include -I/usr/lib/jvm/graalvm-ce-1.0.0-rc12/jre/languages/python/include -c pandas/io/msgpack/_unpacker.cpp -o build/temp.linux-x86_64-3.7/pandas/io/msgpack/_unpacker.o -Wno-unused-function
pandas/io/msgpack/_unpacker.cpp:481:14: fatal error: 'cstdlib' file not found
    #include <cstdlib>
             ^~~~~~~~~
1 error generated.
/usr/lib/jvm/graalvm-ce-1.0.0-rc12/jre/languages/python/bin/graalpython -LD -allowcpp build/temp.linux-x86_64-3.7/pandas/io/msgpack/_unpacker.o -o build/lib.linux-x86_64-3.7/pandas/io/msgpack/_unpacker.bc
llvm-nm: build/temp.linux-x86_64-3.7/pandas/io/msgpack/_unpacker.o: No such file or directory.
llvm-nm: build/temp.linux-x86_64-3.7/pandas/io/msgpack/_unpacker.o: No such file or directory.
llvm-link: build/temp.linux-x86_64-3.7/pandas/io/msgpack/_unpacker.o: error: Could not open input file: No such file or directory
llvm-link: error loading file 'build/temp.linux-x86_64-3.7/pandas/io/msgpack/_unpacker.o'
```

**Comment by fangerer** [comment]
That's actually a good catch and could explain the problem. Please check if you have `libc++-dev` installed.

**Comment by crakjie** [comment]
I have installed `libc++-dev` uninstalled pandas and recompile/install it. And it worked!
`libc++-dev`  could have his place in the future pandas installation guide.

**Comment by fangerer** [comment]
Glad to hear that we could resolve this problem. Yes, I definitively agree, we will include a hint in our README.
Many thanks!
