### ISSUE TITLE
[_functools]: TypeError: __init__() missing 1 required positional argument: 'iterable'

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#62]
I tried to use toolz and got the 

```
Traceback (most recent call last):
  File "wordcount.py", line 8, in <module 'wordcount.py'>
    wordcount = compose(frequencies, map(stem), str.split)
  File "functoolz.py", line 284, in __call__
    return self._partial(*args, **kwargs)
  File "_functools", line 57, in newfunc
TypeError: __init__() missing 1 required positional argument: 'iterable'
```

**Comment by fangerer** [comment]
Hi Ryuta,

sorry for not commenting on this issue for such a long time and thanks for reporting it.
I'm able to reproduce the problem and will investigate the cause.

- Florian

**Comment by fangerer** [comment]
This problem is fixed in master and I could successfully import `toolz`.

**Comment by oroppas** [comment]
Hi Florian, I confirm the fix work. Thank you!
