### ISSUE TITLE
ValueError when using pygments

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#64]
Code from [here](http://pygments.org/docs/quickstart/):
```python
from pygments import highlight
from pygments.lexers import PythonLexer
from pygments.formatters import HtmlFormatter

code = 'print "Hello World"'
print(highlight(code, PythonLexer(), HtmlFormatter()))
```

Error:
```
>>> print(highlight(code, PythonLexer(), HtmlFormatter()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module '<expression>'>
  File "lexer.py", line 580, in __call__
    cls._tokens = cls.process_tokendef('', cls.get_tokendefs())
  File "lexer.py", line 519, in process_tokendef
    cls._process_state(tokendefs, processed, state)
  File "lexer.py", line 482, in _process_state
    tokens.extend(cls._process_state(unprocessed, processed,
  File "lexer.py", line 500, in _process_state
    raise ValueError("uncompilable regex %r in state %r of %r: %s" %
ValueError: uncompilable regex <pygments.lexer.words object at 0x2090933c> in state 'builtins' of <class 'pygments.lexers.python.PythonLexer'>: bad escape \p at position 363
```

**Comment by timfel** [comment]
Ok, we've found the problems that prevented this from running, but it will take a little while to fix them properly.

**Comment by fniephaus** [comment]
Thanks for the update. In the meantime, we decided to use TruffleRuby and Rouge for syntax highlighting ;)

**Comment by timfel** [comment]
As of https://github.com/graalvm/graalpython/commit/17b132fe3da3986c696dc80082f0e550eb748ad4,
your snippet works if you run with `--python.WithTRegex=false`. It will be a few days until the TRegex bug is fixed, this will use the C regex engine, which is slower

**Comment by timfel** [comment]
Resolved in master
