### ISSUE TITLE
Unable to print pandas dataframe

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#65]
```python
import pandas as pd
df = pd.read_csv('data.csv')
print(df)
```

```python
<class 'pandas.core.frame.DataFrame'>
Traceback (most recent call last):
  File "read_csv.py", line 6, in <module 'read_csv.py'>
  File "base.py", line 51, in __str__
  File "frame.py", line 585, in __unicode__
  File "frame.py", line 1529, in to_string
  "/home/ryutas/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/formats/format.py", line 584, in to_string
  "/home/ryutas/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/formats/format.py", line 495, in _to_str_columns
  "/home/ryutas/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/formats/format.py", line 795, in _get_formatted_index
  "/home/ryutas/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/formats/format.py", line 795, in _get_formatted_index.<locals>.<genexp>:/home/ryutas/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/formats/format.py:795
  "/home/ryutas/.local/lib/python3.7/site-packages/pandas-0.20.3-py3.7-linux-x86_64.egg/pandas/io/formats/format.py", line 2238, in _make_fixed_width
java.lang.ClassCastException: com.oracle.graal.python.builtins.objects.cext.PythonAbstractNativeObject cannot be cast to java.lang.Boolean
```

**Comment by timfel** [comment]
Yes, we are aware of this problem. We were busy with larger refactorings but we're getting back to this now :)

**Comment by oroppas** [comment]
master branch starts to fail load `pandas` after re-installing `pandas` by

```
$ graalpython -m ginstall install pandas
```

```
$ graalpython ./read_csv.py 
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "read_csv.py", line 1, in <module 'read_csv.py'>
    import pandas as pd
  File "_bootstrap.py", line 1086, in __import__
  File "_bootstrap.py", line 1006, in _gcd_import
  File "_bootstrap.py", line 983, in _find_and_load
  File "_bootstrap.py", line 967, in _find_and_load_unlocked
  File "_bootstrap.py", line 677, in _load_unlocked
  File "_bootstrap_external.py", line 731, in exec_module
  File "_bootstrap.py", line 219, in _call_with_frames_removed
  File "__init__.py", line 32, in <module '__init__.py'>
    raise ImportError("C extension: {0} not built. If you want to import "
ImportError: C extension: 'hashtable' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
```

I realized the failures to build pandas

```
UPDATING build/lib.linux-x86_64-3.7/pandas/_version.py
set build/lib.linux-x86_64-3.7/pandas/_version.py to '0.20.3'
running build_ext
cythoning pandas/_libs/lib.pyx to pandas/_libs/lib.c
/home/ryutas/.local/lib/python3.7/site-packages/Cython-0.29.2-py3.7.egg/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/tmpv9dwd_bt/pandas-0.20.3/pandas/_libs/lib.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
    from cpython cimport PyString_GET_SIZE
except ImportError:
    from cpython cimport PyUnicode_GET_SIZE as PyString_GET_SIZE

cdef extern from "Python.h":
    Py_ssize_t PY_SSIZE_T_MAX
              ^
------------------------------------------------------------

pandas/_libs/lib.pyx:39:15: Syntax error in C variable declaration
building 'pandas._libs.lib' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/pandas
creating build/temp.linux-x86_64-3.7/pandas/_libs
/home/ryutas/packages/graal/graal/vm/mxbuild/linux-amd64/GRAALVM_CE_PYN/graalvm-ce-1.0.0-rc16-dev/jre/languages/python/bin/graalpython --experimental-options -CC -DNDEBUG -O1 -allowcpp -fPIC -Ipandas/_libs/src/klib -Ipandas/_libs/src -I/home/ryutas/.local/lib/python3.7/site-packages/numpy-1.14.3-py3.7-linux-x86_64.egg/numpy/core/include -I/home/ryutas/packages/graal/graal/vm/mxbuild/linux-amd64/GRAALVM_CE_PYN/graalvm-ce-1.0.0-rc16-dev/jre/languages/python/include -c pandas/_libs/lib.c -o build/temp.linux-x86_64-3.7/pandas/_libs/lib.o -Wno-unused-function
pandas/_libs/lib.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
/home/ryutas/packages/graal/graal/vm/mxbuild/linux-amd64/GRAALVM_CE_PYN/graalvm-ce-1.0.0-rc16-dev/jre/languages/python/bin/graalpython --experimental-options -LD -allowcpp build/temp.linux-x86_64-3.7/pandas/_libs/lib.o -o build/lib.linux-x86_64-3.7/pandas/_libs/lib.bc
llvm-nm: build/temp.linux-x86_64-3.7/pandas/_libs/lib.o: No such file or directory.
llvm-nm: build/temp.linux-x86_64-3.7/pandas/_libs/lib.o: No such file or directory.
llvm-link: build/temp.linux-x86_64-3.7/pandas/_libs/lib.o: error: Could not open input file: No such file or directory
llvm-link: error loading file 'build/temp.linux-x86_64-3.7/pandas/_libs/lib.o'
```

Similar failure of cythoning happens to `pandas/_libs/hashtable.pyx`, etc.

**Comment by timfel** [comment]
`ginstall` is installing `pandas` from a release package, where Cython sources are already generated. What you're seeing seems to indicate there's a different problem. Do you also have e.g. a Python 3.7 installed and did you install pandas through that? Did you delete pandas before reinstalling?

**Comment by timfel** [comment]
We definitely cannot Cythonize the sources for pandas, we don't support enough for Cython to run

**Comment by oroppas** [comment]
Hi @timfel,

Thank you for the status of cython.
Deleting my local installation an re-installing fixed this problem.

**Comment by fangerer** [comment]
Hi Ryuta,
this issue is now fixed (in master). Please verify and feel free to re-open or create new issues if you experience related problems.

**Comment by oroppas** [comment]
Hi Florian,

Thank you! I confirm the fix.
