### ISSUE TITLE
AttributeError: 'OSError' object has no attribute 'errno'

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#67]
https://docs.python.org/3/library/exceptions.html?highlight=errno#OSError.errno

**Comment by timfel** [comment]
Many of our `OSError` objects have the errno set, it's only in some code paths that we don't do it. Can you share what you did so we know which path you're interested in?

**Comment by oroppas** [comment]
chainer (https://github.com/chainer/chainer) requires filelock (https://github.com/benediktschmitt/py-filelock) and I got the following when I `graalpython setup.py test`:

```python
Traceback (most recent call last):
  File "setup.py", line 46, in <module 'setup.py'>
    setup(
  File "/u/yokohama55/people/ryutas/.local/lib/python3.7/site-packages/setuptools-40.8.0.post20190310-py3.7.egg/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "core.py", line 148, in setup
    dist.run_commands()
  File "dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "dist.py", line 985, in run_command
    cmd_obj.run()
  File "/u/yokohama55/people/ryutas/.local/lib/python3.7/site-packages/setuptools-40.8.0.post20190310-py3.7.egg/setuptools/command/test.py", line 228, in run
    self.run_tests()
  File "/u/yokohama55/people/ryutas/.local/lib/python3.7/site-packages/setuptools-40.8.0.post20190310-py3.7.egg/setuptools/command/test.py", line 246, in run_tests
    test = unittest.main(
  File "main.py", line 101, in __init__
    self.runTests()
  File "main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "runner.py", line 176, in run
    test(result)
  File "suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "suite.py", line 122, in run
    test(result)
  File "suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "suite.py", line 122, in run
    test(result)
  File "suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "suite.py", line 122, in run
    test(result)
  File "case.py", line 663, in __call__
    return self.run(*args, **kwds)
  File "case.py", line 611, in run
    self.setUp()
  File "test.py", line 88, in setUp
    if e.errno != errno.ENOENT:
AttributeError: 'OSError' object has no attribute 'errno'
```
