### ISSUE TITLE
[re] bug in compile or match

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#68]
I think graalpython's `re` module fails to correctly compile the expression.
Here's how to reproduce.

```python
import textfsm

def testFSMRule():
  print(textfsm.TextFSMRule('  ^A beer called ${beer} -> Next Next Next'))

if __name__ == '__main__':
  testFSMRule()
```

GraalPython:
```
  ^A beer called ${beer} -> Next Next
```

CPython:
```
Traceback (most recent call last):
  File "testFSMRule.py", line 16, in <module>
    testFSMRule()
  File "testFSMRule.py", line 9, in testFSMRule
    print(textfsm.TextFSMRule('  ^A beer called ${beer} -> Next Next Next'))
  File "/home/ryutas/graalpython/textfsm/textfsm/textfsm/parser.py", line 489, in __init__
    (line, self.line_num))
textfsm.parser.TextFSMTemplateError: Badly formatted rule '^A beer called ${beer} -> Next Next Next'. Line: -1.
```

Relevant lines in `textfsm/parser.py`:

```python
478:    # Attempt to match line.record operation.
479:    action_re = self.ACTION_RE.match(match_action.group('action'))
480:    if not action_re:
481:      # Attempt to match record operation.
482:      action_re = self.ACTION2_RE.match(match_action.group('action'))
483:      if not action_re:
484:        # Math implicit defaults with an optional new state.
485:        action_re = self.ACTION3_RE.match(match_action.group('action'))
486:        if not action_re:
487:          # Last attempt, match an optional new state only.
488:          raise TextFSMTemplateError("Badly formatted rule '%s'. Line: %s." %
489:                                     (line, self.line_num))
```

and `ACTION_RE`, `ACTION2_RE`, and `ACTION3_RE` are defined in:

```python
418:  # Compound operator (line and record) with optional new state.
419:  ACTION_RE = re.compile(r'\s+%s(\s+%s)?$' % (OPERATOR_RE, NEWSTATE_RE))
420:  # Record operator with optional new state.
421:  ACTION2_RE = re.compile(r'\s+%s(\s+%s)?$' % (RECORD_OP_RE, NEWSTATE_RE))
422:  # Default operators with optional new state.
423:  ACTION3_RE = re.compile(r'(\s+%s)?$' % (NEWSTATE_RE))
```

**Comment by timfel** [comment]
Yes, I think this is the same issue as in #64. There are some bugs in our TRegex engine. Thanks for the additional examples!

**Comment by oroppas** [comment]
@timfel 
Thanks for the info. I wait for the fix in TRegex.

**Comment by oroppas** [comment]
I tested by graalpython from master and it behaves correctly.
