### ISSUE TITLE
time.localtime missing, best steps to contribute?

### ISSUE THREAD

**Issue by smarr** [graalvm/graalpython#7]
After porting [ReBench](http://github.com/smarr/ReBench) to Python 3, and having it running on CPython and PyPy, I thought I take it for a spin on GraalPython:

```bash
graalpython --jvm ~/Projects/ReBench/main.py --help
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "_bootstrap.py", line 957, in _find_and_load_unlocked
  File "_bootstrap.py", line 662, in _load_unlocked
  File "_bootstrap_external.py", line 687, in _LoaderBasics.exec_module
  File "_bootstrap.py", line 206, in _call_with_frames_removed
  File "functions", line 106, in exec
  File "Projects/ReBench/rebench/rebench.py", line 30, in <module>
    b'import logging'
  File "_bootstrap.py", line 1066, in __import__
  File "_bootstrap.py", line 985, in _gcd_import
  File "_bootstrap.py", line 968, in _find_and_load
  File "_bootstrap.py", line 957, in _find_and_load_unlocked
  File "_bootstrap.py", line 662, in _load_unlocked
  File "_bootstrap_external.py", line 687, in _LoaderBasics.exec_module
  File "_bootstrap.py", line 206, in _call_with_frames_removed
  File "functions", line 106, in exec
  File "graalvm-1.0.0-rc1/Contents/Home/jre/languages/python/lib-python/3/logging/__init__.py", line 426, in <module>
    b'class Formatter(object):'
  File "classes", line 115, in __build_class__
  File "classes", line 47, in new_class
  File "graalvm-1.0.0-rc1/Contents/Home/jre/languages/python/lib-python/3/logging/__init__.py", line 468, in Formatter
    b'converter = time.localtime'
AttributeError: 'module' object has no attribute localtime
```

Assuming that this `localtime` property might be useful eventually, what would be the preferred approach for me to take to possibly contribute an implementation?

Thanks

**Comment by timfel** [comment]
@cosminbasca has an implementation of this specifically already in a branch, iirc.

Thank you for the offer. Contributions are welcome in PRs. Nkte however, that at this point contributions may still take a bit of time for us to integrate due to moving parts. Once it settles down we'll also add documentation about how to contribute to make the process clearer.

**Comment by cosminbasca** [comment]
Hi @smarr thanks a lot for the report and support! 

As @timfel mentioned `time.localtime` is now supported, although the `time` module itself is not yet complete. 

Cheers,
Cosmin

**Comment by smarr** [comment]
Thanks guys, I just checked how it looks like with RC3.
Guess, I'll have to wait a little.

With multiprocessing, select, threading, subprocess and probably more being work in progress, using ReBench on GraalVM seems a little further out :)
