### ISSUE TITLE
No module named '_lsprof'

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#73]
```
$ graalpython -c "import cProfile"
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
Traceback (most recent call last):
  File "<string>", line 1, in <module '<string>'>
  File "_bootstrap.py", line 1086, in __import__
  File "_bootstrap.py", line 1006, in _gcd_import
  File "_bootstrap.py", line 983, in _find_and_load
  File "_bootstrap.py", line 967, in _find_and_load_unlocked
  File "_bootstrap.py", line 677, in _load_unlocked
  File "_bootstrap_external.py", line 731, in exec_module
  File "_bootstrap.py", line 219, in _call_with_frames_removed
  File "cProfile.py", line 9, in <module 'cProfile.py'>
    import _lsprof
  File "_bootstrap.py", line 1086, in __import__
  File "_bootstrap.py", line 1006, in _gcd_import
  File "_bootstrap.py", line 983, in _find_and_load
  File "_bootstrap.py", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_lsprof'
```

**Comment by timfel** [comment]
For now we don't have plans to support this anytime soon. We recommend to use the Truffle profiling tools instead.

**Comment by oroppas** [comment]
Okay. Thanks.
