### ISSUE TITLE
Function `__dict__` is not writable

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#74]
GraalPython is unable to import `decorator` (https://github.com/micheles/decorator).
Here's the output from GraalPython

```
__main__
Traceback (most recent call last):
  File "func_dict.py", line 101, in <module 'func_dict.py'>
    _contextmanager = decorator(ContextManager)
  File "func_dict.py", line 83, in decorator
    dec = FunctionMaker.create(
  File "func_dict.py", line 69, in create
    return self.make(body, evaldict, addsource, **attrs)
  File "func_dict.py", line 48, in make
    self.update(func, **attrs)
  File "func_dict.py", line 26, in update
    func.__dict__ = getattr(self, 'dict', {})
AttributeError: attribute '__dict__' of 'function' object is not writable
```

whereas CPython runs without error. The error can be reproduced by the following code:

```python
import sys
import re
import itertools
import inspect
from contextlib import _GeneratorContextManager


class FunctionMaker(object):

    # Atomic get-and-increment provided by the GIL
    _compile_count = itertools.count()

    def __init__(self, func=None, name=None, signature=None,
                 module=None, funcdict=None):
        # func=None happens when decorating a caller
        if name:
            self.name = name
        if signature is not None:
            self.signature = signature
        if module:
            self.module = module


    def update(self, func, **kw):
        func.__name__ = self.name
        func.__dict__ = getattr(self, 'dict', {})


    def make(self, src_templ, evaldict=None, addsource=False, **attrs):
        src = src_templ % vars(self)  # expand name and signature
        evaldict = evaldict or {}
        DEF = re.compile(r'\s*def\s*([_\w][_\w\d]*)\s*\(')
        mo = DEF.search(src)
        name = mo.group(1)  # extract the function name

        filename = '<%s:decorator-gen-%d>' % (
            __file__, next(self._compile_count))

        if not src.endswith('\n'):  # add a newline for old Pythons
            src += '\n'

        code = compile(src, filename, 'single')
        exec(code, evaldict)

        func = evaldict[name]
        if addsource:
            attrs['__source__'] = src
        self.update(func, **attrs)
        return func


    @classmethod
    def create(cls, obj, body, evaldict, defaults=None,
               module=None, addsource=True, **attrs):

        name, rest = obj.strip().split('(', 1)
        signature = rest[:-1]  # strip a right parens
        func = None

        print(module)
        self = cls(func, name, signature, defaults, module)
        ibody = '\n'.join('    ' + line for line in body.splitlines())
        caller = evaldict.get('_call_')  # when called from `decorate`
        if caller and iscoroutinefunction(caller):
            body = ('async def %(name)s(%(signature)s):\n' + ibody).replace(
                'return', 'return await')
        else:
            body = 'def %(name)s(%(signature)s):\n' + ibody
        return self.make(body, evaldict, addsource, **attrs)


def decorate(func, caller, extras=()):
    return fun


def decorator(caller, _func=None):

    name = caller.__name__.lower()

    defaultargs, defaults = '', ()

    evaldict = dict(_call=caller, _decorate_=decorate)
    dec = FunctionMaker.create(
        '%s(func, %s)' % (name, defaultargs),
        'if func is None: return lambda func:  _decorate_(func, _call, (%s))\n'
        'return _decorate_(func, _call, (%s))' % (defaultargs, defaultargs),
        evaldict, module=caller.__module__, __wrapped__=caller)

    return dec



class ContextManager(_GeneratorContextManager):
    def __call__(self, func):
        '''Context manager decorator'''
        return FunctionMaker.create(
            func, "with _self_: return _func_(%(shortsignature)s)",
            dict(_self_=self, _func_=func), __wrapped__=func)


_contextmanager = decorator(ContextManager)
```

**Comment by timfel** [comment]
There's a simple reproducer:
```
def foo(): pass
foo.__dict__ = {}
```

We simply haven't marked the `__dict__` descriptor as setter for functions, only as getter.

**Comment by fuxiocteract** [comment]
Also encountered this problem.

**Comment by fangerer** [comment]
Hi Ryuta, we fixed this problem and I could successfully import module `decorator`.

**Comment by oroppas** [comment]
Hi Florian, I confirm the fix. Thanks!
