### ISSUE TITLE
Eval crash on custom filesystem

### ISSUE THREAD

**Issue by Fuyukai** [graalvm/graalpython#8]
I install a custom filesystem in my code that redirects access to a custom root directory. Running any Python code in a Graal context causes this to happen.

```
[python] WARNING: could not determine Graal.Python's standard library path. You need to pass --python.StdLibHome if you want to use the standard library.
[python] WARNING: could not determine Graal.Python's core path - you may need to pass --python.CoreHome.
org.graalvm.polyglot.PolyglotException: java.lang.ClassCastException: com.oracle.graal.python.builtins.objects.PNone cannot be cast to com.oracle.graal.python.builtins.objects.type.PythonClass
	at com.oracle.graal.python.builtins.Python3Core.findKnownExceptionTypes(Python3Core.java:770)
	at com.oracle.graal.python.builtins.Python3Core.initialize(Python3Core.java:343)
	at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:233)
	at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:72)
	at com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:1875)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.postInitEnv(TruffleLanguage.java:2088)
	at com.oracle.truffle.api.vm.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:315)
	at com.oracle.truffle.api.vm.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:155)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:745)
	at org.graalvm.polyglot.Context.eval(Context.java:311)
	at org.graalvm.polyglot.Context.eval(Context.java:336)
	at tf.veriny.vt1000.application.polyglot.PolyglotApplication.invoke(PolyglotApplication.kt:25)
	at tf.veriny.vt1000.kernel.KernelApplication.invoke(KernelApplication.kt:41)
	at tf.veriny.vt1000.kernel.Kernel.invoke(Kernel.kt:45)
	at tf.veriny.vt1000.VT1000$create$2.invoke(VT1000.kt:54)
	at tf.veriny.vt1000.VT1000$create$2.invoke(VT1000.kt:22)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Original Internal Error: 
java.lang.ClassCastException: com.oracle.graal.python.builtins.objects.PNone cannot be cast to com.oracle.graal.python.builtins.objects.type.PythonClass
	at com.oracle.graal.python.builtins.Python3Core.findKnownExceptionTypes(Python3Core.java:770)
	at com.oracle.graal.python.builtins.Python3Core.initialize(Python3Core.java:343)
	at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:233)
	at com.oracle.graal.python.PythonLanguage.initializeContext(PythonLanguage.java:72)
	at com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:1875)
	at com.oracle.truffle.api.TruffleLanguage$LanguageImpl.postInitEnv(TruffleLanguage.java:2088)
	at com.oracle.truffle.api.vm.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:315)
	at com.oracle.truffle.api.vm.PolyglotLanguageContext.parseCached(PolyglotLanguageContext.java:155)
	at com.oracle.truffle.api.vm.PolyglotContextImpl.eval(PolyglotContextImpl.java:745)
	at org.graalvm.polyglot.Context.eval(Context.java:311)
	at org.graalvm.polyglot.Context.eval(Context.java:336)
	at tf.veriny.vt1000.application.polyglot.PolyglotApplication.invoke(PolyglotApplication.kt:25)
	at tf.veriny.vt1000.kernel.KernelApplication.invoke(KernelApplication.kt:41)
	at tf.veriny.vt1000.kernel.Kernel.invoke(Kernel.kt:45)
	at tf.veriny.vt1000.VT1000$create$2.invoke(VT1000.kt:54)
	at tf.veriny.vt1000.VT1000$create$2.invoke(VT1000.kt:22)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

**Comment by timfel** [comment]
Hi,, thanks for trying this. The error is expected, although we probably should supress the exception, since the important information is right at the very top in the warnings: Python needs to load its core files and standard library from the file system. If you have a custom file system, these directories (under jre/languages/python in the GraalVM distribution) must be available in your custom filesystem, too, and you need to set the options "python.CoreHome" and "python.StdLibHome" to point to the directories "lib-graalpython" and "lib-python/3" in your custom location.
