### ISSUE TITLE
Calling python function from java

### ISSUE THREAD

**Issue by oroppas** [graalvm/graalpython#81]
In java, I'm trying to build context for python function and call the python function
as java function. When I check the members of evaluated context, all I see is `close`.
What am I doing wrong here?

```java
import java.util.*;
import java.io.*;

import org.graalvm.polyglot.*;
import org.graalvm.polyglot.proxy.*;


public class main {
  public static void main(String[] args) {

    try {
      OutputStream myOut = new BufferedOutputStream(new FileOutputStream("demo_polyglot.log"));

      Context context = Context.newBuilder("python")
                                .out(myOut)
                                .allowIO(true)
                                .allowPolyglotAccess(PolyglotAccess.ALL)
                                .build();

      String dir = ".";
      String name = "demo_polyglot.py";
      File file = new File(dir, name);
      assert name.endsWith(".py") : "make sure it's python file";

      String language = Source.findLanguage(file);
      Source source = Source.newBuilder(language, file).build();
      assert file.getName().equals(source.getName());
      assert file.getPath().equals(source.getPath());

      Value func = context.eval(source);

      for (String key : func.getMemberKeys()) {
        System.out.println(key);
      }
      //func.getMember("data").execute("rae2822.txt");
    }
    catch(IOException e) {
      e.printStackTrace();
    }
  }
}
```

Here's `demo_polyglot.py`:

```python
import polyglot

@polyglot.export_value
def data(filename):
  print('I will open \"' + filename + '\"')

  # open file and do something
```

**Comment by oroppas** [comment]
Not sure if it's graalpython issue but I got

```
Exception in thread "main" java.lang.UnsupportedOperationException: Unsupported operation Value.execute(Object...) for 'None'(language: Python, type: <class 'NoneType'>). You can ensure that the operation is supported using Value.canExecute().
	at com.oracle.truffle.polyglot.PolyglotValue.unsupported(PolyglotValue.java:389)
	at com.oracle.truffle.polyglot.PolyglotValue.executeUnsupported(PolyglotValue.java:198)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractExecuteNode.executeShared(PolyglotValue.java:1354)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$ExecuteNode.executeImpl(PolyglotValue.java:1426)
	at com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:94)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:284)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget$OptimizedCallProfiled.call(OptimizedCallTarget.java:872)
	at com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:2008)
	at org.graalvm.polyglot.Value.execute(Value.java:338)
	at main.main(main.java:42)
```

when executing

```java
import java.util.*;
import java.io.*;

import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.PolyglotAccess;
import org.graalvm.polyglot.Source;
import org.graalvm.polyglot.Value;
//import org.graalvm.polyglot.proxy.*;


public class main {
  public static void main(String[] args) {

    try {
      OutputStream myOut = new BufferedOutputStream(new FileOutputStream("demo_polyglot.log"));

      Context context = Context.newBuilder("python")
                               .out(myOut)
                               .allowIO(true)
                               .allowPolyglotAccess(PolyglotAccess.ALL)
                               .build();

      Value func = context.eval("python",
        "def data(filename):" +
        "  print('I will open \"' + filename + '\"')"
      );

      for (String key : func.getMemberKeys()) {
        System.out.println(key);
      }
      func.execute("rae2822.txt");
    }
    catch(IOException e) {
      e.printStackTrace();
    }
  }
}
```

Any help will be greatly appreciated. Thanks!

**Comment by oroppas** [comment]
Is this issue more relevant to graal interoperability rather than graalpython?

**Comment by pbailly** [comment]
Hello,
I faced the same issue as you do, and I think I found a solution.

You are looking for the annotation `@polyglot.export_value`:
```
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Source;
import org.graalvm.polyglot.Value;
import org.junit.Test;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class HelperTest {

    @Test
    public void testPython() {
        Context.Builder builder = Context.newBuilder();
        builder.allowAllAccess(true);
        Context context = builder.build();
        String source = "import polyglot\n" +
                "@polyglot.export_value\n" +
                "def foo(externalInput):\n" +
                "    print('Called with: ' + externalInput)\n" +
                "    return 'Got output'\n\n";

        Source script = Source.create("python", source);
        context.eval(script);
        Value main = context.getPolyglotBindings().getMember("foo");
        assertTrue(main.canExecute());

        Value something = main.execute("myInput");
        assertEquals("Got output", something.asString());
    }
}
```

**Comment by oroppas** [comment]
Hi @pbailly,

Thanks for the solution!

So, basically I have to modify the source from

```
Value func = context.eval(source);
```

```
context.eval(source);
Value func = context.getPolyglotBindings().getMember("data");
```

and now I can call python function in Java.
