### ISSUE TITLE
After build, on run: could not find option with name python.Executable

### ISSUE THREAD

**Issue by nimish** [graalvm/graalpython#82]
Caused by: java.lang.IllegalArgumentException: Could not find option with name python.Executable.
	at com.oracle.truffle.polyglot.OptionValuesImpl.failNotFound(OptionValuesImpl.java:227)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.parseOptions(PolyglotEngineImpl.java:393)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:239)
	at com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:172)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:214)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:505)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1304)
	at com.oracle.graal.python.shell.GraalPythonMain.launch(GraalPythonMain.java:374)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:70)
	at com.oracle.graal.python.shell.GraalPythonMain.main(GraalPythonMain.java:57)

done after a  `../mx/mx build`

**Comment by timfel** [comment]
That's curious. Can you post the output of `../mx/mx sversions`?

**Comment by nimish** [comment]
Here's a pic. Getting weirder errors as well.
<img width="753" alt="errors" src="https://user-images.githubusercontent.com/993805/57974688-719be280-798a-11e9-8c91-ef3141469a0c.png">

**Comment by timfel** [comment]
Ok, this sounds like a build error. Are you sure there were no errors running `mx build`?

**Comment by nimish** [comment]
Nope, not  that stopped the build.

**Comment by timfel** [comment]
The build may not look stopped, but since we're building in parallel some errors that break the build occur midway in the log. There was nothing in the logs of the sort? Also, what system are you on?

**Comment by nimish** [comment]
Let me re-run and post logs. Mac OS X Mojave. I have another laptop on which the build works fine, so it's baffling why it breaks for this particular machine. I can set it all up in docker but I would lose easy IntelliJ integration :(

**Comment by msimacek** [comment]
@nimish Hi, any news on the above?

**Comment by nimish** [comment]
Nope, have lost that particular env :(
