### ISSUE TITLE
Cannot import 3rd party library `pycountry`

### ISSUE THREAD

**Issue by jak-ing** [graalvm/graalpython#83]
### Prerequisites: 

We downloaded `pycountry` from [PyPI](https://files.pythonhosted.org/packages/87/c7/c2c76c3ae4ac79c74c1871ae775ed97b70d475dd90d1e824b1d2fc0cd54f/pycountry-18.12.8.tar.gz), unpacked it and did `mv pycountry-18.12.8/src/pycountry $GRAALVM_HOME/jre/languages/python/lib-python/3`.

### Reproduce error:

1. Run `$GRAALVM_HOME/jre/languages/js/bin/node --polyglot --jvm`
2. Evaluate `Polyglot.eval('python', 'import pycountry')` in the REPL
3. --> An error gets printed and the node session quits. See below for the beginning of the error log, @timfel noted that there's also a second problem with outputting Python stack traces correctly from inside GraalVM.

### Remarks:

Interestingly, we were unable to reproduce the error by stepping through the code using the `--inspect` flag. Also, the error only occurs when using Graal-Node.js; **with Graal-JS everything works as expected.** 

CC @fniephaus 

Beginning of error log:
```
java.lang.ArrayIndexOutOfBoundsException: 6
	at com.oracle.graal.python.builtins.objects.function.PArguments.getPFrame(PArguments.java:191)
	at com.oracle.graal.python.builtins.objects.exception.PBaseException.getPFrame(PBaseException.java:219)
	at com.oracle.graal.python.builtins.objects.traceback.PTraceback.getPFrame(PTraceback.java:79)
	at com.oracle.graal.python.builtins.objects.traceback.TracebackBuiltins$GetTracebackFrameNode.get(TracebackBuiltins.java:69)
	at com.oracle.graal.python.builtins.objects.traceback.TracebackBuiltinsFactory$GetTracebackFrameNodeFactory$GetTracebackFrameNodeGen.executeAndSpecialize(TracebackBuiltinsFactory.java:198)
	at com.oracle.graal.python.builtins.objects.traceback.TracebackBuiltinsFactory$GetTracebackFrameNodeFactory$GetTracebackFrameNodeGen.execute(TracebackBuiltinsFactory.java:190)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode$BuiltinAnyCallNode.execute(BuiltinFunctionRootNode.java:73)
	at com.oracle.graal.python.nodes.function.BuiltinFunctionRootNode.execute(BuiltinFunctionRootNode.java:308)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callProxy(OptimizedCallTarget.java:325)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callRoot(OptimizedCallTarget.java:315)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:302)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:284)
	at org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:239)
	at org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:63)
	at com.oracle.graal.python.nodes.call.InvokeNode.doNoKeywords(InvokeNode.java:217)
	at com.oracle.graal.python.nodes.call.InvokeNodeGen.execute(InvokeNodeGen.java:21)
	at com.oracle.graal.python.nodes.call.CallDispatchNode.callBuiltinFunctionCached(CallDispatchNode.java:110)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeAndSpecialize(CallDispatchNodeGen.java:282)
	at com.oracle.graal.python.nodes.call.CallDispatchNodeGen.executeCall(CallDispatchNodeGen.java:76)
	at com.oracle.graal.python.nodes.call.CallNode$CachedCallNode.builtinFunctionCall(CallNode.java:176)
	at com.oracle.graal.python.nodes.call.CallNodeFactory$CachedCallNodeGen.executeAndSpecialize(CallNodeFactory.java:216)
	at com.oracle.graal.python.nodes.call.CallNodeFactory$CachedCallNodeGen.execute(CallNodeFactory.java:114)
	at com.oracle.graal.python.nodes.call.special.CallUnaryMethodNode$CachedNode.call(CallUnaryMethodNode.java:193)
	at com.oracle.graal.python.nodes.call.special.CallUnaryMethodNodeFactory$CachedNodeGen.executeAndSpecialize(CallUnaryMethodNodeFactory.java:1823)
	at com.oracle.graal.python.nodes.call.special.CallUnaryMethodNodeFactory$CachedNodeGen.executeObject(CallUnaryMethodNodeFactory.java:361)
	at com.oracle.graal.python.builtins.objects.getsetdescriptor.GetSetDescriptorTypeBuiltins$GetSetGetNode.get(GetSetDescriptorTypeBuiltins.java:171)
	at com.oracle.graal.python.builtins.objects.getsetdescriptor.GetSetDescriptorTypeBuiltinsFactory$GetSetGetNodeFactory$GetSetGetNodeGen.executeAndSpecialize(GetSetDescriptorTypeBuiltinsFactory.java:223)
	at com.oracle.graal.python.builtins.objects.getsetdescriptor.GetSetDescriptorTypeBuiltinsFactory$GetSetGetNodeFactory$GetSetGetNodeGen.execute(GetSetDescriptorTypeBuiltinsFactory.java:188)
	at com.oracle.graal.python.nodes.call.special.CallTernaryMethodNode.call(CallTernaryMethodNode.java:72)
```

**Comment by timfel** [comment]
I'm not sure how the bug manifests, but it's in line `51` of `lib-python/3/types.py` - the `tb_frame` accessor throws the exception. You could comment that line out as a workaround:
```
modified   jre/languages/python/lib-python/3/types.py
@@ -48,7 +48,7 @@ try:
 except TypeError:
     tb = sys.exc_info()[2]
     TracebackType = type(tb)
-    FrameType = type(tb.tb_frame)
+    # FrameType = type(tb.tb_frame)
     tb = None; del tb
 
 # For Jython, the following two types are identical
```

**Comment by timfel** [comment]
After reworking the traceback code, this is now fixed.
