### ISSUE TITLE
`Path("someFile").resolve()` throws error on macOS

### ISSUE THREAD

**Issue by fniephaus** [graalvm/graalpython#95]
### Describe the Bug

With python3 there is the pathlib library, that replaces the os.path module. One feature is the method `resolve` that returns an absolute path for the given path object. However, with graalpython on macOS this throws an error.

*Tested on GraalVM CE-19.0.0 on macOS 10.14.5.*

### Steps to Reproduce

1. Start graalpython: `graalpython`
2. Try to resolve a directory in the current working directory:
```
$ graalpython
Python 3.7.0 (Thu May 09 01:04:24 PDT 2019)
[GraalVM CE, Java 1.8.0_212] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> from pathlib import Path
>>> Path("someFile").resolve()
```

### Expected Behavior
```
$ python3
Python 3.7.4 (default, Jul  9 2019, 18:13:23) 
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> Path("someFile").resolve()
PosixPath('/Users/myUser/Desktop/someFile')
```

### Actual Behavior
```
$ graalpython
Python 3.7.0 (Thu May 09 01:04:24 PDT 2019)
[GraalVM CE, Java 1.8.0_212] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> from pathlib import Path
>>> Path("someFile").resolve()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module '<expression>'>
  File "pathlib.py", line 1123, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "pathlib.py", line 342, in resolve
    return _resolve(base, str(path)) or sep
  File "pathlib.py", line 335, in _resolve
    path = _resolve(path, target)
  File "pathlib.py", line 335, in _resolve
    path = _resolve(path, target)
  File "pathlib.py", line 323, in _resolve
    raise RuntimeError("Symlink loop from %r" % newpath)
RuntimeError: Symlink loop from '/Users'
```

### Additional Context
A workaround using the os.path module:
```
$ graalpython
Python 3.7.0 (Thu May 09 01:04:24 PDT 2019)
[GraalVM CE, Java 1.8.0_212] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Please note: This Python implementation is in the very early stages, and can run little more than basic benchmarks at this point.
>>> from pathlib import Path
>>> import os
>>> Path(os.path.realpath("someFile"))
PosixPath('/Users/myUser/Desktop/someFile')
```

/cc @janehmueller

**Comment by timfel** [comment]
Thanks. I happened to come across this today as well, a fix is underway

**Comment by timfel** [comment]
Fixed on master.
